import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient(ShopApiConfig.url,ShopApiConfig.key),$=id=>document.getElementById(id),isTest=localStorage.getItem('mytool_admin_data_mode')==='test',params=new URLSearchParams(location.search);
let products=[],cameraScanner=null,cameraRunning=false,lastCameraCode='';
function notify(t,type='info'){$('message').textContent=t;$('message').className='message '+type}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setBindResult(text,type='') {const box=$('bindResult');if(!box)return;box.textContent=text;box.className='inline-result'+(type?' '+type:'')}
function fill(){const q=$('productSearch').value.trim().toLowerCase(),current=$('productSelect').value,rows=products.filter(p=>!q||String(p.product_name).toLowerCase().includes(q)||String(p.product_id).includes(q));$('productSelect').innerHTML='<option value="">اختر المنتج</option>'+rows.map(p=>'<option value="'+p.product_id+'">'+esc(p.product_name)+' (#'+p.product_id+')</option>').join('');if(current&&rows.some(p=>String(p.product_id)===current))$('productSelect').value=current}
function selected(){return products.find(p=>Number(p.product_id)===Number($('productSelect').value))||null}
function render(){const p=selected();$('externalBarcode').value=p?.barcode||'';$('labelName').textContent=p?.product_name||'اختر منتجًا';$('labelId').textContent=p?'#'+p.product_id:'';$('internalBarcode').innerHTML='';if(p&&window.JsBarcode)JsBarcode('#internalBarcode',String(p.product_id),{format:'CODE128',displayValue:true,height:60,margin:8,fontSize:16});if($('cameraProductHint'))$('cameraProductHint').textContent=p?'المنتج المحدد: '+p.product_name+' (#'+p.product_id+')':'اختر المنتج أولًا.';if(p?.barcode)setBindResult('الباركود المرتبط حاليًا: '+p.barcode,'ok');else if(p)setBindResult('لا يوجد باركود خارجي مربوط بهذا المنتج بعد.');else setBindResult('اختر المنتج، ثم امسح باركود المصنع أو اكتبه واحفظه.')}
async function load(){const{data:s}=await supabase.auth.getSession();if(!s?.session){location.replace('../');return}const{data,error}=await supabase.rpc('admin_get_product_barcodes',{p_is_test:isTest});if(error)return notify('تعذر تحميل المنتجات: '+error.message,'error');products=data||[];fill();const requested=Number(params.get('product')||0);if(requested&&products.some(p=>Number(p.product_id)===requested)){$('productSearch').value=String(requested);fill();$('productSelect').value=String(requested)}render();notify('صفحة الباركود جاهزة.','ok')}
async function existingBarcodeOwner(value){if(!value)return null;const{data,error}=await supabase.rpc('admin_lookup_product_by_barcode',{p_barcode:value,p_is_test:isTest});if(error)return null;return data?.[0]||null}
async function saveExternal(){const p=selected();if(!p){setBindResult('اختر المنتج أولًا.','warn');return}const value=$('externalBarcode').value.trim();if(value){const owner=await existingBarcodeOwner(value);if(owner&&Number(owner.product_id)!==Number(p.product_id)){setBindResult('هذا الباركود مربوط مسبقًا بالمنتج '+(owner.product_name||'')+' (#'+owner.product_id+').','warn');return}}const{data,error}=await supabase.rpc('admin_set_product_barcode',{p_product_id:Number(p.product_id),p_barcode:value||null,p_is_test:isTest});if(error){setBindResult('تعذر حفظ الباركود: '+error.message,'warn');return}p.barcode=data?.[0]?.barcode||null;render();if(value){setBindResult('✅ تم ربط الباركود '+value+' بالمنتج '+p.product_name+' (#'+p.product_id+').','ok');$('cameraStatus').textContent='تم الحفظ والربط بنجاح.'}else{setBindResult('تم حذف ربط الباركود الخارجي.','ok');$('cameraStatus').textContent='تم حذف الربط.'}hideCamera()}
async function testScan(){const code=$('scannerTest').value.trim();if(!code)return;let p=/^\d+$/.test(code)?products.find(x=>Number(x.product_id)===Number(code)):null;if(!p){const{data,error}=await supabase.rpc('admin_lookup_product_by_barcode',{p_barcode:code,p_is_test:isTest});if(error){$('scanResult').textContent='خطأ: '+error.message;return}const hit=data?.[0];if(hit)p=products.find(x=>Number(x.product_id)===Number(hit.product_id))||hit}if(p){$('scanResult').textContent='تم التعرف: '+(p.product_name||'منتج')+' (#'+p.product_id+')';$('productSearch').value=String(p.product_id);fill();$('productSelect').value=String(p.product_id);render()}else $('scanResult').textContent='لم يوجد منتج لهذا الباركود.';$('scannerTest').select()}
function loadCameraLibrary(){if(window.Html5Qrcode)return Promise.resolve();return new Promise((resolve,reject)=>{const old=document.querySelector('script[data-html5-qrcode]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html5-qrcode@2.3.8/html5-qrcode.min.js';s.defer=true;s.dataset.html5Qrcode='1';s.onload=resolve;s.onerror=()=>reject(new Error('تعذر تحميل قارئ الكاميرا'));document.head.appendChild(s)})}
function showCamera(){$('cameraLive')?.classList.remove('hidden')}
function hideCamera(){$('cameraLive')?.classList.add('hidden');$('startCamera').disabled=false}
async function stopCamera(){if(cameraScanner&&cameraRunning){try{await cameraScanner.stop()}catch(_e){}}cameraRunning=false;$('stopCamera').disabled=true;$('startCamera').disabled=false}
async function cameraDecoded(decodedText){const code=String(decodedText||'').trim();if(!code||code===lastCameraCode)return;lastCameraCode=code;await stopCamera();$('externalBarcode').value=code;$('cameraCode').textContent=code;$('cameraCode').classList.remove('hidden');const p=selected();setBindResult(p?'تمت القراءة: '+code+'. راجع الرقم ثم اضغط «حفظ وربط الباركود».':'تمت القراءة، لكن اختر المنتج قبل الحفظ.','ok');$('cameraStatus').textContent='تمت القراءة. الكاميرا متوقفة الآن.';hideCamera()}
async function startCamera(){const p=selected();if(!p){setBindResult('اختر المنتج أولًا حتى لا نربط الباركود بمنتج خاطئ.','warn');$('productSelect').focus();return}if(cameraRunning)return;showCamera();$('cameraStatus').textContent='جاري تشغيل الكاميرا…';try{await loadCameraLibrary();cameraScanner=cameraScanner||new Html5Qrcode('cameraReader');lastCameraCode='';await cameraScanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:150},aspectRatio:1.777778},cameraDecoded,()=>{});cameraRunning=true;$('startCamera').disabled=true;$('stopCamera').disabled=false;$('cameraStatus').textContent='الكاميرا تعمل. وجّهها إلى باركود المصنع.'}catch(error){hideCamera();setBindResult('تعذر تشغيل الكاميرا: '+(error?.message||error)+'. تأكد من إذن الكاميرا.','warn')}}
async function switchTab(name){if(name!=='bind'&&cameraRunning)await stopCamera();document.querySelectorAll('[data-tab]').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===name));document.querySelectorAll('[data-panel]').forEach(panel=>panel.classList.toggle('hidden',panel.dataset.panel!==name))}
$('productSearch').oninput=fill;$('productSelect').onchange=render;$('saveExternal').onclick=saveExternal;$('clearExternal').onclick=()=>{$('externalBarcode').value='';saveExternal()};$('printInternal').onclick=()=>{if(!selected())return notify('اختر المنتج أولًا.','error');window.print()};$('scannerTest').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();testScan()}});$('startCamera')?.addEventListener('click',startCamera);$('stopCamera')?.addEventListener('click',async()=>{await stopCamera();hideCamera()});document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>switchTab(btn.dataset.tab)));window.addEventListener('beforeunload',()=>{if(cameraScanner&&cameraRunning)cameraScanner.stop().catch(()=>{})});load().catch(e=>notify(e.message,'error'));