import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const config=window.ShopApiConfig;if(!config)throw new Error('SHOP_API_CONFIG_MISSING');
const supabase=createClient(config.url,config.key);
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mode=localStorage.getItem('mytool_admin_data_mode')==='test'?'test':'real';let categories=[],products=[],page=1;const PAGE=10;
function notify(text,type='info'){$('message').textContent=text;$('message').className='message '+type}
function activeCategories(){return categories.filter(c=>c.active)}
function categoryOptions(selected,includeInactive=false){const list=includeInactive?categories:activeCategories();return '<option value="">غير مصنف</option>'+list.map(c=>'<option value="'+c.id+'" '+(String(selected||'')===String(c.id)?'selected':'')+'>'+esc(c.name)+(c.active?'':' — معطل')+'</option>').join('')}
function renderCategories(){$('categoryList').innerHTML=categories.map(c=>'<div class="category-row" data-category-row="'+c.id+'"><input class="category-name" value="'+esc(c.name)+'"><input class="category-order" type="number" step="1" value="'+Number(c.sort_order||0)+'"><label class="check"><input class="category-active" type="checkbox" '+(c.active?'checked':'')+'> نشط <span class="badge">'+Number(c.product_count||0)+' منتج</span></label><button type="button" class="btn secondary save-category">حفظ</button></div>').join('')||'<div class="muted">لا توجد تصنيفات.</div>';document.querySelectorAll('[data-category-row]').forEach(row=>row.querySelector('.save-category').onclick=()=>saveCategory(row))}
function fillFilters(){const current=$('productCategoryFilter').value||'all';$('productCategoryFilter').innerHTML='<option value="all">كل التصنيفات</option><option value="uncategorized">غير مصنف</option>'+activeCategories().map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('');if([...$('productCategoryFilter').options].some(o=>o.value===current))$('productCategoryFilter').value=current}
function filtered(){const q=$('productSearch').value.trim().toLowerCase(),cat=$('productCategoryFilter').value,type=$('productTypeFilter').value;return products.filter(p=>(!q||String(p.product_name).toLowerCase().includes(q)||String(p.product_id).includes(q))&&(cat==='all'||(cat==='uncategorized'?!p.category_id:String(p.category_id)===cat))&&(type==='all'||p.item_type===type))}
function renderProducts(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/PAGE));page=Math.min(Math.max(1,page),pages);const start=(page-1)*PAGE,visible=rows.slice(start,start+PAGE);$('catalogSummary').textContent='وضع البيانات: '+(mode==='test'?'تجريبي':'حقيقي')+' — '+rows.length+' عنصر';$('productList').innerHTML=visible.map(p=>'<div class="product-row" data-product-row="'+p.product_id+'"><div class="product-name">'+esc(p.product_name)+'<small>#'+p.product_id+(p.category_name?' — '+esc(p.category_name):' — غير مصنف')+'</small></div><select class="product-category">'+categoryOptions(p.category_id,true)+'</select><select class="product-type"><option value="product" '+(p.item_type==='product'?'selected':'')+'>سلعة / مخزون</option><option value="service" '+(p.item_type==='service'?'selected':'')+'>خدمة</option></select><button type="button" class="btn save-product">حفظ</button></div>').join('')||'<div class="muted">لا توجد نتائج.</div>';$('pageInfo').textContent='صفحة '+page+' من '+pages;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;document.querySelectorAll('[data-product-row]').forEach(row=>row.querySelector('.save-product').onclick=()=>saveProduct(row))}
async function load(){const{data:s}=await supabase.auth.getSession();if(!s?.session){location.replace('../');return}const[c,p]=await Promise.all([supabase.rpc('admin_list_product_categories',{p_include_inactive:true}),supabase.rpc('admin_get_product_catalog',{p_is_test:mode==='test'})]);if(c.error||p.error)return notify('تعذر تحميل الكتالوج: '+(c.error||p.error).message,'error');categories=c.data||[];products=p.data||[];renderCategories();fillFilters();renderProducts();notify('الكتالوج جاهز. يمكنك التصنيف تدريجيًا بدون إجبار المنتجات القديمة.','ok')}
async function saveCategory(row){const id=Number(row.dataset.categoryRow),name=row.querySelector('.category-name').value.trim(),sort=Number(row.querySelector('.category-order').value||0),active=row.querySelector('.category-active').checked;if(!name)return notify('اسم التصنيف مطلوب.','error');notify('جاري حفظ التصنيف…');const{error}=await supabase.rpc('admin_save_product_category',{p_category_id:id,p_name:name,p_active:active,p_sort_order:sort});if(error)return notify('تعذر حفظ التصنيف: '+error.message,'error');await load();notify('تم حفظ التصنيف.','ok')}
async function saveProduct(row){const id=Number(row.dataset.productRow),categoryRaw=row.querySelector('.product-category').value,itemType=row.querySelector('.product-type').value;notify('جاري حفظ المنتج…');const{error}=await supabase.rpc('admin_set_product_catalog_meta',{p_product_id:id,p_category_id:categoryRaw?Number(categoryRaw):null,p_item_type:itemType});if(error){let msg=error.message||'';if(msg.includes('ITEM_TYPE_HAS_STOCK_HISTORY'))msg='لا يمكن تحويل هذه السلعة إلى خدمة لأنها تملك مخزونًا أو سجل حركات. أنشئ خدمة مستقلة بدل تغيير السلعة.';return notify(msg,'error')}await load();notify('تم حفظ التصنيف والنوع.','ok')}
$('newCategoryForm').onsubmit=async e=>{e.preventDefault();const name=$('newCategoryName').value.trim(),sort=Number($('newCategoryOrder').value||0);if(!name)return;notify('جاري إضافة التصنيف…');const{error}=await supabase.rpc('admin_save_product_category',{p_category_id:null,p_name:name,p_active:true,p_sort_order:sort});if(error)return notify('تعذر إضافة التصنيف: '+error.message,'error');$('newCategoryName').value='';await load();notify('تمت إضافة التصنيف.','ok')};
$('productSearch').oninput=()=>{page=1;renderProducts()};$('productCategoryFilter').onchange=()=>{page=1;renderProducts()};$('productTypeFilter').onchange=()=>{page=1;renderProducts()};$('prevPage').onclick=()=>{if(page>1){page--;renderProducts()}};$('nextPage').onclick=()=>{const pages=Math.max(1,Math.ceil(filtered().length/PAGE));if(page<pages){page++;renderProducts()}};load().catch(e=>notify(e.message,'error'));