(function(){
'use strict';
const URL='https://wqyebqzbbpohbnznqdjj.supabase.co/rest/v1/rpc/';
const KEY='sb_publishable_gO4umNBMJ0AWRk19HtKd7A_9X4DibYj';
let state={product:0,branch:0,missingPurchase:false,missingSale:false};
function worker(){return localStorage.getItem('mytool_shop_worker_token')||'';}
function access(){if(worker())return KEY;try{const k=Object.keys(localStorage).find(x=>x.startsWith('sb-')&&x.endsWith('-auth-token'));const v=k?JSON.parse(localStorage.getItem(k)||'null'):null;return v?.access_token||KEY;}catch(_e){return KEY;}}
async function rpc(name,args){const r=await fetch(URL+name,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+access(),'Content-Type':'application/json'},body:JSON.stringify(args)});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.message||('HTTP '+r.status));return data;}
function notify(text,type){const m=document.getElementById('message');if(m){m.textContent=text;m.className='message '+(type||'info');}}
function ensure(){let box=document.getElementById('inventoryPriceSetup');if(box)return box;const anchor=document.getElementById('inventoryCurrent');if(!anchor)return null;box=document.createElement('div');box.id='inventoryPriceSetup';box.className='hint';box.hidden=true;box.innerHTML='<strong>المنتج بلا أسعار كاملة في هذا الفرع</strong><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px"><div id="invPurchaseWrap"><label>سعر الشراء (دج)</label><input id="inventoryPurchasePrice" type="number" min="0" step="0.01"></div><div id="invSaleWrap"><label>سعر البيع (دج)</label><input id="inventorySalePrice" type="number" min="0" step="0.01"></div></div><div id="inventoryPriceGuide" style="margin-top:8px"></div>';anchor.insertAdjacentElement('afterend',box);return box;}
async function load(){const box=ensure(),p=document.getElementById('inventoryProduct'),b=document.getElementById('inventoryBranch');if(!box||!p||!b)return;state={product:Number(p.value),branch:Number(b.value),missingPurchase:false,missingSale:false};box.hidden=true;document.getElementById('inventoryPurchasePrice').value='';document.getElementById('inventorySalePrice').value='';if(!state.product||!state.branch)return;try{const t=worker();const rows=await rpc(t?'worker_get_branch_product_prices':'admin_get_branch_product_prices',t?{p_session_token:t,p_branch_id:state.branch}:{p_branch_id:state.branch});const row=(rows||[]).find(x=>Number(x.product_id)===state.product)||null;state.missingPurchase=!row||row.last_purchase_price==null;state.missingSale=!row||row.last_sale_price==null;if(!state.missingPurchase&&!state.missingSale)return;box.hidden=false;document.getElementById('invPurchaseWrap').hidden=!state.missingPurchase;document.getElementById('invSaleWrap').hidden=!state.missingSale;const guide=await rpc(t?'worker_product_price_guidance':'admin_product_price_guidance',t?{p_session_token:t,p_product_id:state.product,p_current_branch_id:state.branch}:{p_product_id:state.product,p_exclude_branch_id:state.branch});const g=document.getElementById('inventoryPriceGuide');g.innerHTML='<div>أسعار فروع أخرى للاستئناس فقط:</div><div id="inventoryGuideButtons" style="display:flex;gap:6px;flex-wrap:wrap;margin-top:6px"></div>';const h=document.getElementById('inventoryGuideButtons');(guide||[]).forEach(x=>{[['purchase',x.purchase_price],['sale',x.sale_price]].forEach(([kind,val])=>{if(val==null||(kind==='purchase'&&!state.missingPurchase)||(kind==='sale'&&!state.missingSale))return;const bt=document.createElement('button');bt.type='button';bt.className='btn secondary';bt.style.width='auto';bt.textContent=(x.branch_name||'فرع آخر')+' '+(kind==='purchase'?'شراء ':'بيع ')+Number(val).toLocaleString('ar-DZ')+' دج';bt.onclick=()=>{document.getElementById(kind==='purchase'?'inventoryPurchasePrice':'inventorySalePrice').value=String(val);};h.appendChild(bt);});});if(!h.children.length)g.textContent='لا يوجد سعر مرجعي في الفروع الأخرى.';}catch(e){box.hidden=false;document.getElementById('inventoryPriceGuide').textContent='تعذر تحميل الأسعار: '+e.message;}}
async function save(e){const form=document.getElementById('inventoryForm');if(e.target!==form||(!state.missingPurchase&&!state.missingSale))return;e.preventDefault();e.stopImmediatePropagation();const actual=Number(document.getElementById('inventoryActual').value),reason=(document.getElementById('inventoryReason').value||'').trim()||'جرد فعلي';const pp=document.getElementById('inventoryPurchasePrice'),sp=document.getElementById('inventorySalePrice');if(!Number.isInteger(actual)||actual<0)return notify('راجع الكمية الفعلية.','error');if(state.missingPurchase&&pp.value.trim()==='')return notify('أدخل سعر الشراء أو اختر سعرًا استرشاديًا.','error');if(state.missingSale&&sp.value.trim()==='')return notify('أدخل سعر البيع أو اختر سعرًا استرشاديًا.','error');const purchase=state.missingPurchase?Number(pp.value):null,sale=state.missingSale?Number(sp.value):null;if(!confirm('تأكيد الجرد والأسعار؟'))return;try{const t=worker();const args={p_product_id:state.product,p_actual_quantity:actual,p_reason:reason,p_branch_id:state.branch,p_purchase_price:purchase,p_sale_price:sale};const id=await rpc(t?'worker_record_branch_inventory_count_with_prices':'admin_record_branch_inventory_count_with_prices',t?{p_session_token:t,...args}:args);document.getElementById('inventoryActual').value='';document.getElementById('inventoryReason').value='';notify(t&&Number(id)<0?'تم إرسال فرق النقص للإدارة وحفظ الأسعار.':'تم تسجيل الجرد والأسعار بنجاح.','ok');document.getElementById('inventoryBranch').dispatchEvent(new Event('change',{bubbles:true}));setTimeout(load,300);}catch(err){notify('لم يتم حفظ الجرد والأسعار: '+err.message,'error');}}
function start(){if(document.body?.dataset?.screen!=='inventory')return;ensure();const p=document.getElementById('inventoryProduct'),b=document.getElementById('inventoryBranch'),f=document.getElementById('inventoryForm');if(!p||!b||!f)return;const later=()=>setTimeout(load,180);p.addEventListener('change',later);b.addEventListener('change',later);f.addEventListener('submit',save,true);later();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();