/* Quick pricing for the selected product. Admin only. */
(function(){'use strict';
const screen=document.body?.dataset?.screen||'';
const cfg={sale:['saleProduct','saleBranch'],purchase:['purchaseProduct','purchaseBranch'],inventory:['inventoryProduct','inventoryBranch']}[screen];
if(!cfg||localStorage.getItem('mytool_shop_worker_token'))return;
const $=id=>document.getElementById(id),api=window.ShopApiConfig;let dbPromise,current={product:0,branch:0,policy:null};
const db=()=>dbPromise||(dbPromise=import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm').then(m=>m.createClient(api.url,api.key)));
const money=v=>v==null?'—':Number(v).toLocaleString('ar-DZ',{maximumFractionDigits:2})+' دج';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(name,args){const c=await db(),r=await c.rpc(name,args);if(r.error)throw r.error;return r.data||[]}
function pageMessage(text,type='ok'){const m=$('message')||$('purchaseMessage');if(!m)return;m.textContent=text;m.className='message '+type;m.classList.remove('hidden')}
function selected(){const p=$(cfg[0]),b=$(cfg[1]);return{product:Number(p?.value||0),branch:Number(b?.value||0),productName:p?.selectedOptions?.[0]?.textContent||'',branchName:b?.selectedOptions?.[0]?.textContent||''}}
function close(){ $('quickPricingOverlay')?.classList.add('hidden') }
function style(){if($('quickPricingStyle'))return;const s=document.createElement('style');s.id='quickPricingStyle';s.textContent='.quick-price-bar{display:flex;justify-content:flex-end;margin:7px 0}.quick-price-btn{width:auto!important;padding:8px 12px!important;border:1px solid #0f766e!important;border-radius:10px!important;background:#fff!important;color:#0f766e!important;font-weight:900!important}.qp-overlay{position:fixed;inset:0;background:#0f172a80;z-index:400;display:flex;align-items:flex-end;justify-content:center;padding:10px}.qp-overlay.hidden{display:none!important}.qp-sheet{width:min(720px,100%);max-height:90dvh;overflow:auto;background:#fff;border-radius:20px 20px 14px 14px;padding:16px}.qp-head{display:flex;justify-content:space-between;gap:10px}.qp-close{width:42px!important;height:42px;padding:0!important;background:#fff!important;border:1px solid #e5e7eb!important;font-size:24px}.qp-meta{color:#6b7280;font-size:12px;line-height:1.6}.qp-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.qp-stat{padding:9px;border:1px solid #e5e7eb;border-radius:11px;background:#f8fafc}.qp-stat small{display:block;color:#6b7280}.qp-field{margin-top:10px}.qp-field label{display:block;font-size:12px;font-weight:900;margin-bottom:5px}.qp-field input{width:100%;padding:11px;border:1px solid #e5e7eb;border-radius:11px;font:inherit}.qp-guide{border:1px solid #e5e7eb;border-radius:12px;padding:10px;margin-top:7px}.qp-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.qp-save{background:#0f766e!important;color:#fff!important;border:0!important;font-weight:900!important}.qp-secondary{background:#fff!important;color:#0f766e!important;border:1px solid #0f766e!important;font-weight:900!important}@media(max-width:560px){.qp-stats,.qp-actions{grid-template-columns:1fr}}';document.head.appendChild(s)}
function fullPolicy(){const u=new URL('pricing-policy.html',location.href);u.searchParams.set('branch',current.branch);u.searchParams.set('product',current.product);location.href=u.href}
function modal(){let o=$('quickPricingOverlay');if(o)return o;style();o=document.createElement('div');o.id='quickPricingOverlay';o.className='qp-overlay hidden';o.innerHTML='<section class="qp-sheet"><div class="qp-head"><div><h2 style="margin:0">تسعير المنتج</h2><div id="qpMeta" class="qp-meta"></div></div><button id="qpClose" class="qp-close" type="button">×</button></div><div id="qpStatus" class="qp-meta" style="margin-top:8px"></div><div id="qpStats" class="qp-stats"></div><form id="qpForm"><div class="qp-field"><label>سعر البيع المعتمد (دج)</label><input id="qpTargetSale" type="number" min="0" step="0.01"></div><div class="qp-field"><label>مرجع شراء تشغيلي — اختياري</label><input id="qpWorkerRef" type="number" min="0" step="0.01"><div class="qp-meta">مرجع تشغيلي فقط؛ لا يغيّر تكلفة الشراء الحقيقية.</div></div><div style="margin-top:12px;font-weight:900">أسعار الفروع الأخرى للاستئناس</div><div id="qpGuides"></div><div class="qp-actions"><button class="qp-save" type="submit">حفظ السعر</button><button id="qpFull" class="qp-secondary" type="button">السياسة الكاملة</button></div></form></section>';document.body.appendChild(o);$('qpClose').onclick=close;$('qpFull').onclick=fullPolicy;$('qpForm').onsubmit=save;o.onclick=e=>{if(e.target===o)close()};return o}
function guides(rows){const root=$('qpGuides');root.innerHTML=rows.length?rows.map(x=>'<div class="qp-guide"><b>'+esc(x.branch_name||'فرع آخر')+'</b><div class="qp-meta">شراء: '+money(x.purchase_price)+' — بيع: '+money(x.sale_price)+'</div>'+(x.sale_price!=null?'<button type="button" class="qp-secondary" data-sale="'+esc(x.sale_price)+'">نسخ سعر البيع</button>':'')+(x.purchase_price!=null?'<button type="button" class="qp-secondary" data-ref="'+esc(x.purchase_price)+'">نسخ كمرجع شراء</button>':'')+'</div>').join(''):'<div class="qp-meta">لا توجد أسعار مرجعية في الفروع الأخرى.</div>';root.querySelectorAll('[data-sale]').forEach(b=>b.onclick=()=>{$('qpTargetSale').value=b.dataset.sale});root.querySelectorAll('[data-ref]').forEach(b=>b.onclick=()=>{$('qpWorkerRef').value=b.dataset.ref})}
async function open(){const s=selected();current.product=s.product;current.branch=s.branch;if(!s.product||!s.branch)return pageMessage('اختر المنتج والفرع أولًا.','error');modal().classList.remove('hidden');$('qpMeta').textContent=s.productName+' — '+s.branchName;$('qpStatus').textContent='جاري تحميل السعر…';$('qpStats').innerHTML='';$('qpGuides').innerHTML='';try{const [policies,prices,refs]=await Promise.all([rpc('admin_get_branch_product_sale_policy',{p_branch_id:s.branch}),rpc('admin_get_branch_product_prices',{p_branch_id:s.branch}),rpc('admin_product_price_guidance',{p_product_id:s.product,p_exclude_branch_id:s.branch})]);const p=policies.find(x=>Number(x.product_id)===s.product)||null,r=prices.find(x=>Number(x.product_id)===s.product)||null;current.policy=p;$('qpStats').innerHTML='<div class="qp-stat"><small>التكلفة الحقيقية</small><b>'+money(p?.true_cost??r?.weighted_average_purchase)+'</b></div><div class="qp-stat"><small>آخر شراء</small><b>'+money(r?.last_purchase_price)+'</b></div><div class="qp-stat"><small>الحد الأدنى الحالي</small><b>'+money(p?.minimum_sale_price)+'</b></div>';$('qpTargetSale').value=p?.target_sale_price??r?.last_sale_price??'';$('qpWorkerRef').value=p?.worker_reference_purchase_price??'';guides(refs);$('qpStatus').textContent=p?.review_required?'تنبيه: التكلفة تغيرت؛ راجع السعر قبل الحفظ.':'يمكن تعديل السعر بدون تسجيل جرد أو بيع أو شراء.'}catch(e){$('qpStatus').textContent='تعذر تحميل التسعير: '+e.message}}
async function save(e){e.preventDefault();const target=$('qpTargetSale').value.trim()===''?null:Number($('qpTargetSale').value),ref=$('qpWorkerRef').value.trim()===''?null:Number($('qpWorkerRef').value),p=current.policy||{};if(target!=null&&(!Number.isFinite(target)||target<0))return $('qpStatus').textContent='سعر البيع غير صحيح.';try{$('qpStatus').textContent='جاري الحفظ…';await rpc('admin_set_branch_product_sale_policy',{p_branch_id:current.branch,p_product_id:current.product,p_target_sale_price:target,p_minimum_mode:p.minimum_mode||'cost_floor',p_minimum_value:p.minimum_value??null,p_worker_reference_purchase_price:ref,p_show_minimum_to_worker:p.show_minimum_to_worker!==false});if(screen==='sale'&&$('salePrice')&&target!=null)$('salePrice').value=String(target);window.dispatchEvent(new CustomEvent('shop:pricing-refresh',{detail:{productId:current.product,branchId:current.branch}}));close();pageMessage('تم حفظ سعر المنتج بدون تسجيل جرد أو عملية أخرى.','ok')}catch(err){$('qpStatus').textContent='تعذر حفظ السعر: '+err.message}}
function ensureButton(){const p=$(cfg[0]);if(!p)return;let bar=$('quickPricingBar');if(!bar){bar=document.createElement('div');bar.id='quickPricingBar';bar.className='quick-price-bar';bar.innerHTML='<button id="quickPricingButton" class="quick-price-btn" type="button">تسعير هذا المنتج</button>';const picker=p.parentElement?.querySelector('[data-catalog-picker]');(picker||p).insertAdjacentElement('afterend',bar);$('quickPricingButton').onclick=open}const s=selected();bar.hidden=!(s.product&&s.branch)}
function start(attempt=0){const p=$(cfg[0]),b=$(cfg[1]);if(!p||!b){if(attempt<60)setTimeout(()=>start(attempt+1),150);return}ensureButton();p.addEventListener('change',ensureButton);b.addEventListener('change',ensureButton)}
window.MyToolQuickPricing={open};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>start(),{once:true});else start();
})();