/* MyTool quick pricing modal for the currently selected product.
 * Admin-only. Keeps the user on sale/purchase/inventory screens.
 */
(function(){
'use strict';
const screen=document.body?.dataset?.screen||'';
const cfg={sale:{product:'saleProduct',branch:'saleBranch'},purchase:{product:'purchaseProduct',branch:'purchaseBranch'},inventory:{product:'inventoryProduct',branch:'inventoryBranch'}}[screen];
if(!cfg||localStorage.getItem('mytool_shop_worker_token'))return;
const URL='https://wqyebqzbbpohbnznqdjj.supabase.co/rest/v1/rpc/';
const KEY='sb_publishable_gO4umNBMJ0AWRk19HtKd7A_9X4DibYj';
let current={product:0,branch:0,policy:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v===null||v===undefined?'—':Number(v).toLocaleString('ar-DZ',{maximumFractionDigits:2})+' دج';
function access(){try{const k=Object.keys(localStorage).find(x=>x.startsWith('sb-')&&x.endsWith('-auth-token'));const v=k?JSON.parse(localStorage.getItem(k)||'null'):null;return v?.access_token||KEY;}catch(_e){return KEY;}}
async function rpc(name,args){const r=await fetch(URL+name,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+access(),'Content-Type':'application/json'},body:JSON.stringify(args||{})});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.message||('HTTP '+r.status));return data;}
function pageMessage(text,type='ok'){const m=$('message')||$('purchaseMessage');if(!m)return;m.textContent=text;m.className='message '+type;m.classList.remove('hidden');}
function ensureStyle(){if($('quickPricingStyle'))return;const s=document.createElement('style');s.id='quickPricingStyle';s.textContent=`.quick-price-bar{display:flex;justify-content:flex-end;margin:7px 0}.quick-price-btn{width:auto!important;padding:8px 12px!important;border:1px solid #0f766e!important;border-radius:10px!important;background:#fff!important;color:#0f766e!important;font-weight:900!important}.qp-overlay{position:fixed;inset:0;background:#0f172a80;z-index:400;display:flex;align-items:flex-end;justify-content:center;padding:10px}.qp-overlay.hidden{display:none!important}.qp-sheet{width:min(720px,100%);max-height:90dvh;overflow:auto;background:#fff;border-radius:20px 20px 14px 14px;padding:16px;box-shadow:0 -18px 45px #0f172a40}.qp-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.qp-close{width:42px!important;height:42px;padding:0!important;border:1px solid #e5e7eb!important;background:#fff!important;color:#172033!important;font-size:24px}.qp-meta{color:#6b7280;font-size:12px;line-height:1.6}.qp-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.qp-stat{padding:9px;border:1px solid #e5e7eb;border-radius:11px;background:#f8fafc}.qp-stat small{display:block;color:#6b7280}.qp-stat b{display:block;margin-top:4px}.qp-field{margin-top:10px}.qp-field label{display:block;font-size:12px;font-weight:900;margin-bottom:5px}.qp-field input{width:100%;padding:11px;border:1px solid #e5e7eb;border-radius:11px;font:inherit}.qp-guides{display:grid;gap:7px;margin-top:10px}.qp-guide{border:1px solid #e5e7eb;border-radius:12px;padding:10px}.qp-guide-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.qp-guide-actions button{width:auto!important;padding:7px 9px!important}.qp-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.qp-save{background:#0f766e!important;color:#fff!important;border:0!important;font-weight:900!important}.qp-secondary{background:#fff!important;color:#0f766e!important;border:1px solid #0f766e!important;font-weight:900!important}@media(max-width:560px){.qp-stats{grid-template-columns:1fr}.qp-sheet{padding:13px}.qp-actions{grid-template-columns:1fr}}`;
document.head.appendChild(s);}
function ensureModal(){let o=$('quickPricingOverlay');if(o)return o;ensureStyle();o=document.createElement('div');o.id='quickPricingOverlay';o.className='qp-overlay hidden';o.innerHTML='<section class="qp-sheet" role="dialog" aria-modal="true" aria-labelledby="qpTitle"><div class="qp-head"><div><h2 id="qpTitle" style="margin:0">تسعير المنتج</h2><div id="qpMeta" class="qp-meta"></div></div><button id="qpClose" class="qp-close" type="button">×</button></div><div id="qpStatus" class="qp-meta" style="margin-top:8px">جاري التحميل…</div><div id="qpStats" class="qp-stats"></div><form id="qpForm"><div class="qp-field"><label>سعر البيع المعتمد (دج)</label><input id="qpTargetSale" type="number" min="0" step="0.01" inputmode="decimal"></div><div class="qp-field"><label>مرجع شراء تشغيلي — اختياري</label><input id="qpWorkerRef" type="number" min="0" step="0.01" inputmode="decimal"><div class="qp-meta">مرجع تشغيلي فقط؛ لا يغيّر تكلفة الشراء المحاسبية الحقيقية.</div></div><div style="margin-top:12px;font-weight:900">أسعار الفروع الأخرى للاستئناس</div><div id="qpGuides" class="qp-guides"></div><div class="qp-actions"><button class="qp-save" type="submit">حفظ السعر</button><button id="qpFull" class="qp-secondary" type="button">السياسة الكاملة</button></div></form></section>';
document.body.appendChild(o);const close=()=>o.classList.add('hidden');$('qpClose').onclick=close;o.addEventListener('click',e=>{if(e.target===o)close()});$('qpFull').onclick=()=>location.href='pricing-policy.html';$('qpForm').onsubmit=save;return o;}
function selected(){const p=$(cfg.product),b=$(cfg.branch);return{product:Number(p?.value||0),branch:Number(b?.value||0),productName:p?.selectedOptions?.[0]?.textContent||'',branchName:b?.selectedOptions?.[0]?.textContent||''};}
function ensureButton(){const p=$(cfg.product);if(!p)return null;let bar=$('quickPricingBar');if(bar)return bar;bar=document.createElement('div');bar.id='quickPricingBar';bar.className='quick-price-bar';bar.innerHTML='<button id="quickPricingButton" class="quick-price-btn" type="button">تسعير هذا المنتج</button>';const picker=p.parentElement?.querySelector('[data-catalog-picker]');(picker||p).insertAdjacentElement('afterend',bar);$('quickPricingButton').onclick=()=>open();syncButton();return bar;}
function syncButton(){const bar=$('quickPricingBar');if(!bar)return;const s=selected();bar.hidden=!(s.product&&s.branch);}
function renderGuides(rows){const root=$('qpGuides');if(!rows?.length){root.innerHTML='<div class="qp-meta">لا توجد أسعار مرجعية في الفروع الأخرى.</div>';return}root.innerHTML=rows.map((x,i)=>'<div class="qp-guide"><b>'+esc(x.branch_name||('فرع '+(i+1)))+'</b><div class="qp-meta">شراء: '+money(x.purchase_price)+' — بيع: '+money(x.sale_price)+'</div><div class="qp-guide-actions">'+(x.sale_price!=null?'<button type="button" class="qp-secondary" data-qpsale="'+esc(x.sale_price)+'">نسخ سعر البيع</button>':'')+(x.purchase_price!=null?'<button type="button" class="qp-secondary" data-qpref="'+esc(x.purchase_price)+'">نسخ كمرجع شراء</button>':'')+'</div></div>').join('');root.querySelectorAll('[data-qpsale]').forEach(b=>b.onclick=()=>{$('qpTargetSale').value=b.dataset.qpsale});root.querySelectorAll('[data-qpref]').forEach(b=>b.onclick=()=>{$('qpWorkerRef').value=b.dataset.qpref});}
async function open(productId,branchId){const s=selected();current.product=Number(productId||s.product);current.branch=Number(branchId||s.branch);if(!current.product||!current.branch)return pageMessage('اختر المنتج والفرع أولًا.','error');const overlay=ensureModal();overlay.classList.remove('hidden');$('qpMeta').textContent=(s.productName||('منتج #'+current.product))+' — '+(s.branchName||('فرع #'+current.branch));$('qpStatus').textContent='جاري تحميل السعر…';$('qpStats').innerHTML='';$('qpGuides').innerHTML='';$('qpTargetSale').value='';$('qpWorkerRef').value='';try{const [policies,prices,guides]=await Promise.all([rpc('admin_get_branch_product_sale_policy',{p_branch_id:current.branch}),rpc('admin_get_branch_product_prices',{p_branch_id:current.branch}),rpc('admin_product_price_guidance',{p_product_id:current.product,p_exclude_branch_id:current.branch})]);const policy=(policies||[]).find(x=>Number(x.product_id)===current.product)||null;const price=(prices||[]).find(x=>Number(x.product_id)===current.product)||null;current.policy=policy;$('qpStats').innerHTML='<div class="qp-stat"><small>التكلفة الحقيقية</small><b>'+money(policy?.true_cost??price?.weighted_average_purchase)+'</b></div><div class="qp-stat"><small>آخر شراء</small><b>'+money(price?.last_purchase_price)+'</b></div><div class="qp-stat"><small>الحد الأدنى الحالي</small><b>'+money(policy?.minimum_sale_price)+'</b></div>';$('qpTargetSale').value=policy?.target_sale_price??price?.last_sale_price??'';$('qpWorkerRef').value=policy?.worker_reference_purchase_price??'';renderGuides(guides||[]);$('qpStatus').textContent=policy?.review_required?'تنبيه: التكلفة تغيرت؛ راجع السعر قبل الحفظ.':'يمكن تعديل سعر البيع فقط بدون تسجيل جرد أو بيع أو شراء.';}catch(e){$('qpStatus').textContent='تعذر تحميل التسعير: '+e.message;}}
async function save(e){e.preventDefault();const target=$('qpTargetSale').value.trim()===''?null:Number($('qpTargetSale').value),ref=$('qpWorkerRef').value.trim()===''?null:Number($('qpWorkerRef').value),p=current.policy||{};if(target!==null&&(!Number.isFinite(target)||target<0))return $('qpStatus').textContent='سعر البيع غير صحيح.';if(ref!==null&&(!Number.isFinite(ref)||ref<0))return $('qpStatus').textContent='مرجع الشراء غير صحيح.';$('qpStatus').textContent='جاري الحفظ…';try{await rpc('admin_set_branch_product_sale_policy',{p_branch_id:current.branch,p_product_id:current.product,p_target_sale_price:target,p_minimum_mode:p.minimum_mode||'cost_floor',p_minimum_value:p.minimum_value??null,p_worker_reference_purchase_price:ref,p_show_minimum_to_worker:p.show_minimum_to_worker!==false});if(screen==='sale'&&$('salePrice')&&target!==null){$('salePrice').value=String(target);$('salePrice').dispatchEvent(new Event('change',{bubbles:true}))}window.dispatchEvent(new CustomEvent('shop:pricing-refresh',{detail:{productId:current.product,branchId:current.branch}}));pageMessage('تم حفظ سعر المنتج بدون تسجيل جرد أو عملية أخرى.','ok');$('qpStatus').textContent='تم الحفظ بنجاح.';setTimeout(()=>$('quickPricingOverlay')?.classList.add('hidden'),450);}catch(err){$('qpStatus').textContent='تعذر حفظ السعر: '+err.message;}}
function start(attempt=0){const p=$(cfg.product),b=$(cfg.branch);if(!p||!b){if(attempt<60)setTimeout(()=>start(attempt+1),180);return}ensureButton();p.addEventListener('change',syncButton);b.addEventListener('change',syncButton);new MutationObserver(()=>{if(!$('quickPricingBar'))ensureButton();syncButton()}).observe(p.parentElement,{childList:true,subtree:true});syncButton();}
window.MyToolQuickPricing={open};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>start(),{once:true});else start();
})();
