(() => {
'use strict';
let mode=false,sub='linked',sortMode='debt',timer=0,draft={a:'',b:'',sa:[],sb:[],step:'a'},addTo={linkId:'',sourceId:'',rowKey:''};
const C=()=>window.MyToolAccountLinks;
const toast=(t,e=false)=>window.MyToolBottomNav?.toast?.(t,e);
function netBadge(balance,debt,c){const n=(Number(balance)||0)-(Number(debt)||0),cls=n<0?'negative':n>0?'positive':'zero',sign=n>0?'+':n<0?'−':'';return '<span class="customer-net '+cls+'">صافي '+sign+c.num(Math.abs(n))+'</span>'}
function mini(x){const c=C();return '<div class="link-mini"><div><div class="link-title-row"><strong>'+c.esc(c.name(x.r))+'</strong>'+netBadge(x.r.balance,x.r.debt,c)+'</div><small>'+c.esc(x.r.username||'—')+' · '+c.esc(x.s.name)+'</small></div><div class="link-ident">'+(x.r.phone?'<span>📞 '+c.esc(x.r.phone)+'</span>':'')+(x.r.email?'<span>✉ '+c.esc(x.r.email)+'</span>':'')+'</div><div class="link-money"><span class="metric debt">دين <b>'+c.num(x.r.debt)+'</b></span><span class="metric balance">رصيد <b>'+c.num(x.r.balance)+'</b></span><span class="metric profit">أرباح <b>'+c.num(x.r.profit)+'</b></span></div></div>'}
function linkTotals(l,st){const c=C(),xs=l.members.map(m=>c.resolve(m,st.ss)).filter(x=>x.r);return{balance:xs.reduce((a,x)=>a+(+x.r.balance||0),0),debt:xs.reduce((a,x)=>a+(+x.r.debt||0),0),profit:xs.reduce((a,x)=>a+(+x.r.profit||0),0)}}
function sortLabel(){return sortMode==='debt'?'الدين':sortMode==='balance'?'الرصيد':'الأرباح'}
function resolvedMembers(l,st){const c=C();return(l.members||[]).map(m=>c.resolve(m,st.ss)).filter(x=>x?.s&&x?.r)}
function validSharedLinks(st){return(st.ls||[]).filter(l=>{const xs=resolvedMembers(l,st);return xs.length>=2&&new Set(xs.map(x=>x.s.id)).size>=2})}
function sharedTotals(st){return validSharedLinks(st).reduce((a,l)=>{const t=linkTotals(l,st);a.balance+=t.balance;a.debt+=t.debt;a.profit+=t.profit;return a},{balance:0,debt:0,profit:0})}
function sortedLinks(st){const c=C();return validSharedLinks(st).sort((a,b)=>{const av=linkTotals(a,st)[sortMode]||0,bv=linkTotals(b,st)[sortMode]||0;if(bv!==av)return bv-av;const an=a.displayName||c.name(c.resolve(a.members[0],st.ss)?.r),bn=b.displayName||c.name(c.resolve(b.members[0],st.ss)?.r);return String(an||'').localeCompare(String(bn||''),'ar')})}
function addBox(l,st){const c=C();if(addTo.linkId!==l.id)return'';const used=new Set((l.members||[]).map(m=>m.sourceId)),sources=st.ss.filter(s=>!used.has(s.id)),selected=sources.find(s=>s.id===addTo.sourceId),rows=selected?c.unlinked(selected,st):[];return '<div class="link-add-box"><label>المصدر<select data-add-source="'+c.esc(l.id)+'"><option value="">اختر المصدر</option>'+sources.map(s=>'<option value="'+c.esc(s.id)+'" '+(s.id===addTo.sourceId?'selected':'')+'>'+c.esc(s.name)+'</option>').join('')+'</select></label><label>الحساب<select data-add-row="'+c.esc(l.id)+'"><option value="">اختر الحساب</option>'+rows.map(r=>'<option value="'+c.esc(String(r.key))+'" '+(String(r.key)===String(addTo.rowKey)?'selected':'')+'>'+c.esc(c.name(r))+' — '+c.esc(r.username||'—')+'</option>').join('')+'</select></label><div class="link-add-actions"><button data-add-confirm="'+c.esc(l.id)+'" '+(addTo.sourceId&&addTo.rowKey?'':'disabled')+'>إضافة للحساب المشترك</button><button class="secondary-lite" data-add-cancel="'+c.esc(l.id)+'">إلغاء</button></div></div>'}
function linkCard(l,st){const c=C(),xs=l.members.map(m=>c.resolve(m,st.ss)),ok=xs.filter(x=>x.r),miss=xs.length-ok.length,t=linkTotals(l,st),b=t.balance,d=t.debt,p=t.profit,sources=[...new Set(ok.map(x=>x.s?.name).filter(Boolean))];return '<article data-link-card="'+c.esc(l.id)+'" class="shared-card'+(miss?' needs-review':'')+'"><header><div><div class="shared-title-row"><strong>'+c.esc(l.displayName||c.name(ok[0]?.r))+'</strong>'+netBadge(b,d,c)+'</div><small>مشترك في: '+sources.map(c.esc).join('، ')+(miss?' · يحتاج مراجعة':'')+'</small></div><div class="shared-head-actions"><button data-add-open="'+c.esc(l.id)+'">إضافة حساب</button><button data-rename="'+c.esc(l.id)+'">تسمية</button></div></header>'+addBox(l,st)+'<div class="shared-members">'+xs.map(x=>x.r?'<div class="shared-member">'+mini(x)+'<button data-unlink="'+c.esc(l.id)+'|'+c.esc(x.m.sourceId)+'|'+c.esc(x.m.rowKey)+'">فك</button></div>':'<div class="shared-member missing"><span>'+c.esc(x.m.sourceName)+' — غير موجود في آخر تحديث</span><button data-unlink="'+c.esc(l.id)+'|'+c.esc(x.m.sourceId)+'|'+c.esc(x.m.rowKey)+'">فك</button></div>').join('')+'</div><footer><div class="shared-total"><span class="metric debt">الدين <b>'+c.num(d)+'</b></span><span class="metric balance">الرصيد <b>'+c.num(b)+'</b></span><span class="metric profit">الأرباح <b>'+c.num(p)+'</b></span></div><button class="danger-lite" data-unlink-all="'+c.esc(l.id)+'">فك العلاقة</button></footer></article>'}
function sugCard(s){const c=C();return '<article class="suggest-card'+(s.review?' needs-review':'')+'"><div class="suggest-reason"><b>تطابق '+c.esc(s.by)+'</b><small>'+(s.review?'مراجعة: '+c.esc(s.bad.join('، ')):'اقتراح فقط — يحتاج اعتماد')+'</small></div><div class="suggest-pair">'+mini(s.a)+mini(s.b)+'</div><div class="suggest-actions"><button data-approve="'+c.esc(s.id)+'">اعتماد</button><button class="secondary-lite" data-dismiss="'+c.esc(s.id)+'">تجاهل</button></div></article>'}
function list(s,side,st){const c=C();if(!s)return'<div class="shared-empty">اختر المصدر.</div>';const sel=side==='a'?draft.sa:draft.sb;return '<div class="draft-list">'+c.unlinked(s,st).map(r=>{const k=String(r.key),i=sel.indexOf(k),n=i<0?'':i+1;return '<label class="draft-row'+(n?' selected':'')+'"><input type="checkbox" data-side="'+side+'" value="'+c.esc(k)+'" '+(n?'checked':'')+'><span class="draft-order">'+n+'</span><span><strong>'+c.esc(c.name(r))+'</strong><small>'+c.esc(r.username||'—')+'</small></span><b>'+c.num(r.debt)+'</b></label>'}).join('')+'</div>'}
function review(st){const c=C(),a=st.ss.find(x=>x.id===draft.a),b=st.ss.find(x=>x.id===draft.b);if(!a||!b)return'<div class="shared-empty">اختر مصدرين.</div>';if(!draft.sa.length||draft.sa.length!==draft.sb.length)return'<div class="shared-empty">نفس العدد مطلوب. الأولى '+draft.sa.length+' — الثانية '+draft.sb.length+'</div>';return '<div class="pair-review">'+draft.sa.map((ka,i)=>{const ra=a.rows.find(r=>String(r.key)===ka),rb=b.rows.find(r=>String(r.key)===draft.sb[i]);return ra&&rb?'<article><div class="pair-number">#'+(i+1)+'</div>'+mini({s:a,r:ra})+'<div class="pair-arrow">↔</div>'+mini({s:b,r:rb})+'<div class="pair-order-actions"><button data-move="'+i+'|-1" '+(i?'':'disabled')+'>↑</button><button data-move="'+i+'|1" '+(i<draft.sb.length-1?'':'disabled')+'>↓</button></div></article>':''}).join('')+'</div><button class="approve-batch" data-approve-batch>اعتماد '+draft.sa.length+' علاقة</button>'}
function manual(st){const c=C();if(st.ss.length<2)return'<div class="shared-empty">نحتاج مصدرين على الأقل.</div>';const o=st.ss.map(s=>'<option value="'+c.esc(s.id)+'">'+c.esc(s.name)+'</option>').join(''),a=st.ss.find(x=>x.id===draft.a),b=st.ss.find(x=>x.id===draft.b);return '<div class="manual-link"><div class="source-pickers"><label>الأولى<select data-a><option value="">اختر</option>'+o+'</select></label><label>الثانية<select data-b><option value="">اختر</option>'+o+'</select></label></div><div class="draft-tabs"><button data-step="a" class="'+(draft.step==='a'?'active':'')+'">الأولى ('+draft.sa.length+')</button><button data-step="b" class="'+(draft.step==='b'?'active':'')+'">الثانية ('+draft.sb.length+')</button><button data-step="review" class="'+(draft.step==='review'?'active':'')+'">مراجعة</button></div>'+(draft.step==='a'?list(a,'a',st):draft.step==='b'?list(b,'b',st):review(st))+'</div>'}
function panelBase(){const tabs=document.querySelector('.tabs');if(!tabs)return null;let t=document.getElementById('accountsSharedTab');if(!t){t=document.createElement('button');t.id='accountsSharedTab';t.className='tab accounts-shared-tab';t.type='button';t.textContent='المشتركة';t.onclick=enter;const total=document.getElementById('accountsTotalTab');if(total)total.insertAdjacentElement('afterend',t);else tabs.prepend(t)}let p=document.getElementById('accountsSharedPanel');if(!p){p=document.createElement('section');p.id='accountsSharedPanel';p.className='panel accounts-shared-panel';tabs.closest('section.panel')?.insertAdjacentElement('afterend',p)}return p}
function hide(){const app=document.getElementById('app'),tp=document.querySelector('.tabs')?.closest('section.panel'),p=document.getElementById('accountsSharedPanel');[...(app?.children||[])].forEach(x=>{if(x===tp||x===p||x.classList?.contains('hero')||x.classList?.contains('msg'))return;if(x.tagName==='SECTION'&&!x.dataset.sharedHidden){x.dataset.sharedHidden=x.hidden?'1':'0';x.hidden=true}})}
function restore(){document.querySelectorAll('[data-shared-hidden]').forEach(x=>{x.hidden=x.dataset.sharedHidden==='1';delete x.dataset.sharedHidden})}
async function enter(){mode=true;window.dispatchEvent(new Event('accounts-shared-selected'));const total=document.getElementById('accountsTotalPanel');if(total){total.hidden=true;total.style.display='none'}document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.remove('active'));const p=panelBase();if(p){p.hidden=false;p.style.removeProperty('display')}document.getElementById('accountsSharedTab').classList.add('active');await render();hide();nav()}
function exit(){const wasActive=mode;mode=false;const p=document.getElementById('accountsSharedPanel');if(p){p.hidden=true;p.style.display='none'}restore();if(wasActive)window.dispatchEvent(new Event('accounts-shared-exit'))}
async function render(){const c=C();if(!c)return;const st=await c.state(),sg=c.suggestions(st),good=sg.filter(x=>!x.review),rev=sg.filter(x=>x.review),linked=sortedLinks(st),totals=sharedTotals(st),p=panelBase();const tab=document.getElementById('accountsSharedTab');if(tab)tab.innerHTML='المشتركة <small>('+linked.length+')</small>';if(!p)return;p.innerHTML='<div class="shared-head"><div><h2>الحسابات المشتركة</h2><p>القيم هنا تخص الحسابات المشتركة فقط.</p></div>'+(sub==='linked'?'<button type="button" class="shared-sort sort-'+sortMode+'" data-sort-cycle>ترتيب: '+sortLabel()+' ↓</button>':'')+'</div><div class="summary shared-summary"><div class="stat debt"><span>إجمالي ديون المشتركة</span><strong>'+c.num(totals.debt)+'</strong></div><div class="stat balance"><span>إجمالي أرصدة المشتركة</span><strong>'+c.num(totals.balance)+'</strong></div><div class="stat profit"><span>إجمالي أرباح المشتركة</span><strong>'+c.num(totals.profit)+'</strong></div></div><div class="shared-subtabs"><button data-sub="linked" class="'+(sub==='linked'?'active':'')+'">مرتبط ('+linked.length+')</button><button data-sub="suggestions" class="'+(sub==='suggestions'?'active':'')+'">اقتراحات ('+good.length+')</button><button data-sub="review" class="'+(sub==='review'?'active':'')+'">مراجعة ('+rev.length+')</button><button data-sub="manual" class="'+(sub==='manual'?'active':'')+'">ربط يدوي</button></div><div class="shared-body">'+(sub==='linked'?(linked.length?linked.map(l=>linkCard(l,st)).join(''):'<div class="shared-empty">لا توجد علاقات.</div>'):sub==='suggestions'?(good.length?good.map(sugCard).join(''):'<div class="shared-empty">لا توجد اقتراحات.</div>'):sub==='review'?(rev.length?rev.map(sugCard).join(''):'<div class="shared-empty">لا توجد تعارضات.</div>'):manual(st))+'</div>';p.hidden=!mode;if(mode)hide();bind(p,st);nav()}
function bind(p,st){const c=C();p.querySelector('[data-sort-cycle]')?.addEventListener('click',()=>{sortMode=sortMode==='debt'?'balance':sortMode==='balance'?'profit':'debt';render()});p.querySelectorAll('[data-add-open]').forEach(x=>x.onclick=()=>{addTo={linkId:x.dataset.addOpen,sourceId:'',rowKey:''};render()});p.querySelectorAll('[data-add-cancel]').forEach(x=>x.onclick=()=>{addTo={linkId:'',sourceId:'',rowKey:''};render()});p.querySelectorAll('[data-add-source]').forEach(x=>x.onchange=()=>{addTo.sourceId=x.value;addTo.rowKey='';render()});p.querySelectorAll('[data-add-row]').forEach(x=>x.onchange=()=>{addTo.rowKey=x.value;render()});p.querySelectorAll('[data-add-confirm]').forEach(x=>x.onclick=async()=>{const id=x.dataset.addConfirm;if(!addTo.sourceId||!addTo.rowKey)return;const res=await c.addMember(id,addTo.sourceId,addTo.rowKey);if(!res?.ok){toast(res?.reason==='linked_elsewhere'?'هذا الحساب مربوط بعلاقة أخرى':'تعذر إضافة الحساب',true);return}addTo={linkId:'',sourceId:'',rowKey:''};toast('تمت إضافة الحساب للعلاقة');window.dispatchEvent(new Event('accounts-identities-updated'));render()});p.querySelectorAll('[data-sub]').forEach(x=>x.onclick=()=>{sub=x.dataset.sub;render()});p.querySelectorAll('[data-approve]').forEach(x=>x.onclick=async()=>{await c.approve(x.dataset.approve);toast('تم اعتماد العلاقة');render()});p.querySelectorAll('[data-dismiss]').forEach(x=>x.onclick=async()=>{await c.dismiss(x.dataset.dismiss);toast('تم تجاهل الاقتراح');render()});p.querySelectorAll('[data-unlink-all]').forEach(x=>x.onclick=async()=>{if(confirm('فك العلاقة؟ السجلات الأصلية لن تُحذف.')){await c.unlinkAll(x.dataset.unlinkAll);toast('تم فك العلاقة');render()}});p.querySelectorAll('[data-rename]').forEach(x=>x.onclick=async()=>{const n=prompt('اسم العلاقة');if(n!==null){await c.rename(x.dataset.rename,n);render()}});p.querySelectorAll('[data-unlink]').forEach(x=>x.onclick=async()=>{const [l,s,k]=x.dataset.unlink.split('|');await c.unlinkMember(l,s,k);toast('تم فك الحساب');render()});const a=p.querySelector('[data-a]'),b=p.querySelector('[data-b]');if(a){a.value=draft.a;a.onchange=()=>{draft.a=a.value;draft.sa=[];if(draft.a===draft.b){draft.b='';draft.sb=[]}render()}}if(b){b.value=draft.b;b.onchange=()=>{draft.b=b.value;draft.sb=[];if(draft.a===draft.b){draft.a='';draft.sa=[]}render()}}p.querySelectorAll('[data-step]').forEach(x=>x.onclick=()=>{draft.step=x.dataset.step;render()});p.querySelectorAll('[data-side]').forEach(x=>x.onchange=()=>{const s=x.dataset.side==='a'?draft.sa:draft.sb,k=String(x.value),i=s.indexOf(k);if(x.checked&&i<0)s.push(k);if(!x.checked&&i>=0)s.splice(i,1);render()});p.querySelectorAll('[data-move]').forEach(x=>x.onclick=()=>{const [i,d]=x.dataset.move.split('|').map(Number),j=i+d;if(j>=0&&j<draft.sb.length)[draft.sb[i],draft.sb[j]]=[draft.sb[j],draft.sb[i]];render()});p.querySelector('[data-approve-batch]')?.addEventListener('click',()=>batch(st))}
async function batch(st){const c=C(),a=st.ss.find(x=>x.id===draft.a),b=st.ss.find(x=>x.id===draft.b);if(!a||!b||!draft.sa.length||draft.sa.length!==draft.sb.length){toast('الاختيار غير مكتمل',true);return}for(let i=0;i<draft.sa.length;i++){const ra=a.rows.find(r=>String(r.key)===draft.sa[i]),rb=b.rows.find(r=>String(r.key)===draft.sb[i]);if(ra&&rb)await c.pair({s:a,r:ra},{s:b,r:rb})}const n=draft.sa.length;draft={a:'',b:'',sa:[],sb:[],step:'a'};sub='linked';toast('تم اعتماد '+n+' علاقة');render()}
async function copy(){const c=C(),st=await c.state(),lines=['الحسابات المشتركة','عدد العلاقات: '+st.ls.length,''];for(const l of st.ls){const xs=l.members.map(m=>c.resolve(m,st.ss)).filter(x=>x.r);lines.push((l.displayName||c.name(xs[0]?.r))+' — '+xs.length+' حساب');xs.forEach(x=>lines.push(x.s.name+': '+(x.r.username||'—')+' | رصيد '+c.num(x.r.balance)+' | دين '+c.num(x.r.debt)));lines.push('')}try{await navigator.clipboard.writeText(lines.join('\n'));toast('تم النسخ')}catch{toast('تعذر النسخ',true)}}
async function openSourceLinkRequest(event){const c=C(),d=event.detail||{},st=await c.state(),s=st.ss.find(x=>x.id===d.sourceId),r=s?.rows?.find(x=>String(x.key)===String(d.rowKey));if(!s||!r){toast('تعذر العثور على الحساب',true);return}const linkId=st.map.get(c.rid(s.id,r));if(linkId){sub='linked';addTo={linkId,sourceId:'',rowKey:''};await enter();setTimeout(()=>{const card=[...document.querySelectorAll('[data-link-card]')].find(x=>x.dataset.linkCard===linkId);card?.scrollIntoView({behavior:'smooth',block:'center'})},120);return}addTo={linkId:'',sourceId:'',rowKey:''};draft={a:s.id,b:'',sa:[String(r.key)],sb:[],step:'b'};sub='manual';await enter()}
function nav(){if(!mode||!window.MyToolBottomNav)return;window.MyToolBottomNav.setActions([{slot:1,icon:'🔗',label:'ربط',onClick:()=>{sub='manual';render()}},{slot:2,icon:'📂',label:'ملف',onClick:()=>document.querySelector('input[type="file"][multiple]')?.click()},{icon:'📋',label:'نسخ المشتركة',overflow:true,onClick:copy},{icon:'🔄',label:'تحديث',overflow:true,onClick:render}])}
let statusTimer=0;
async function decorateSourceLinkStatus(){
  const c=C(),cards=[...document.querySelectorAll('.source-account-card[data-source-id][data-row-key]')];if(!c||!cards.length)return;
  const st=await c.state();
  for(const card of cards){
    const sid=card.dataset.sourceId,key=String(card.dataset.rowKey||''),s=st.ss.find(x=>x.id===sid),r=s?.rows?.find(x=>String(x.key)===key),box=card.querySelector('[data-link-status]'),btn=card.querySelector('.source-link-btn');
    if(!box||!s||!r)continue;
    const linkId=st.map.get(c.rid(s.id,r)),link=linkId?st.ls.find(x=>x.id===linkId):null;
    const others=link?[...new Set((link.members||[]).map(m=>c.resolve(m,st.ss)).filter(x=>x?.s&&x?.r&&x.s.id!==s.id).map(x=>x.s.name).filter(Boolean))]:[];
    const linked=others.length>0,text=linked?'مربوط بـ: '+others.join('، '):'غير مربوط';
    if(box.textContent!==text)box.textContent=text;
    box.classList.toggle('linked',linked);box.classList.toggle('unlinked',!linked);
    if(btn)btn.textContent=linked?'🔗 إضافة / إدارة الربط':'🔗 إضافة / ربط';
  }
}
function scheduleStatus(){clearTimeout(statusTimer);statusTimer=setTimeout(()=>decorateSourceLinkStatus().catch(()=>{}),80)}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>render().catch(()=>{}),120);scheduleStatus()}
function start(){const app=document.getElementById('app');if(!app||!C())return;panelBase();schedule();app.addEventListener('click',e=>{const t=e.target.closest('.tab');if(t&&t.id!=='accountsSharedTab'&&mode){exit();setTimeout(schedule,80)}},true);window.addEventListener('accounts-link-request',openSourceLinkRequest);window.addEventListener('accounts-total-selected',()=>{if(mode)exit();const p=document.getElementById('accountsSharedPanel');if(p){p.hidden=true;p.style.display='none'}});window.addEventListener('accounts-source-selected',()=>{if(mode)exit();const p=document.getElementById('accountsSharedPanel');if(p){p.hidden=true;p.style.display='none'}scheduleStatus();setTimeout(scheduleStatus,180)});window.addEventListener('accounts-identities-updated',()=>{schedule();scheduleStatus()});window.addEventListener('mytool-bottom-nav-ready',()=>mode&&nav());new MutationObserver(()=>{if(!document.getElementById('accountsSharedTab'))panelBase();scheduleStatus()}).observe(app,{childList:true,subtree:true})}
if(C())start();else window.addEventListener('mytool-account-links-core-ready',start,{once:true});
})();
