
-- MyTool Flexy accounts/wallet/order foundation.
-- 2026-09-19
-- Business wallet is a Flexy subledger linked to the existing immutable journal core.

create extension if not exists pgcrypto with schema extensions;

insert into public.accounts(
  branch_id, system_code, name, account_type, account_subtype,
  currency_code, active, is_system, notes
)
values (
  null,
  'FLEXY_SUBLEDGER_CONTROL',
  'حساب مقابل محافظ Flexy',
  'equity',
  'flexy_subledger_control',
  'DZD',
  true,
  true,
  'حساب رقابي داخلي لموازنة حركات أرصدة وديون Flexy. ليس محفظة عميل.'
)
on conflict (system_code) do nothing;

create table if not exists public.flexy_accounts (
  id bigint generated by default as identity primary key,
  account_uuid uuid not null default gen_random_uuid() unique,
  display_name text not null,
  username text,
  status text not null default 'active'
    check (status in ('active','blocked','archived')),
  account_rate_percent numeric(9,4) not null default 0
    check (account_rate_percent >= 0),
  allow_debt boolean not null default false,
  currency_code text not null default 'DZD'
    check (currency_code ~ '^[A-Z]{3}$'),
  credit_ledger_account_id bigint not null unique
    references public.accounts(id) on delete restrict,
  debt_ledger_account_id bigint not null unique
    references public.accounts(id) on delete restrict,
  core_identity_type text,
  core_identity_ref text,
  notes text,
  created_by_admin_user_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (nullif(btrim(display_name),'') is not null)
);

create unique index if not exists flexy_accounts_username_unique
  on public.flexy_accounts(lower(username))
  where username is not null and btrim(username) <> '';

create unique index if not exists flexy_accounts_core_identity_unique
  on public.flexy_accounts(core_identity_type,core_identity_ref)
  where core_identity_type is not null and core_identity_ref is not null;

create index if not exists flexy_accounts_status_idx
  on public.flexy_accounts(status,id desc);

create table if not exists public.flexy_orders (
  id bigint generated by default as identity primary key,
  order_uuid uuid not null default gen_random_uuid() unique,
  account_id bigint not null
    references public.flexy_accounts(id) on delete restrict,
  request_key text not null,
  phone text not null,
  operator text not null default 'mobilis',
  service_type text not null default 'offer',
  family text,
  network_index text,
  face_amount numeric(18,2) not null check (face_amount > 0),
  purchase_price numeric(18,2),
  sale_price numeric(18,2),
  wallet_charge_amount numeric(18,2) not null check (wallet_charge_amount > 0),
  profit_amount numeric(18,2),
  rate_percent_applied numeric(9,4) not null default 0,
  funding_mode text
    check (funding_mode is null or funding_mode in ('credit','debt','mixed')),
  status text not null default 'created'
    check (status in (
      'created','reserved','queued','claimed','execution_started',
      'success','failed','review','cancelled'
    )),
  station_job_uuid uuid unique
    references public.station_connect_jobs(job_uuid) on delete set null,
  result_code text,
  result_text text,
  created_by_admin_user_id uuid,
  created_at timestamptz not null default now(),
  reserved_at timestamptz,
  queued_at timestamptz,
  execution_started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(account_id,request_key),
  check (phone ~ '^0[5-7][0-9]{8}$')
);

create index if not exists flexy_orders_queue_idx
  on public.flexy_orders(status,created_at,id);

create index if not exists flexy_orders_account_idx
  on public.flexy_orders(account_id,created_at desc,id desc);

create table if not exists public.flexy_wallet_holds (
  id bigint generated by default as identity primary key,
  hold_uuid uuid not null default gen_random_uuid() unique,
  order_id bigint not null unique
    references public.flexy_orders(id) on delete restrict,
  account_id bigint not null
    references public.flexy_accounts(id) on delete restrict,
  credit_amount numeric(18,2) not null default 0 check (credit_amount >= 0),
  debt_amount numeric(18,2) not null default 0 check (debt_amount >= 0),
  status text not null default 'active'
    check (status in ('active','review','captured','released')),
  created_at timestamptz not null default now(),
  captured_at timestamptz,
  released_at timestamptz,
  updated_at timestamptz not null default now(),
  check (credit_amount + debt_amount > 0)
);

create index if not exists flexy_wallet_holds_account_status_idx
  on public.flexy_wallet_holds(account_id,status,created_at);

create table if not exists public.flexy_account_events (
  id bigint generated by default as identity primary key,
  event_uuid uuid not null default gen_random_uuid() unique,
  account_id bigint not null
    references public.flexy_accounts(id) on delete restrict,
  order_id bigint
    references public.flexy_orders(id) on delete set null,
  event_type text not null
    check (event_type in (
      'credit','debt','payment','refund',
      'order_capture','order_release','adjustment','reversal'
    )),
  amount numeric(18,2) not null check (amount > 0),
  credit_delta numeric(18,2) not null default 0,
  debt_delta numeric(18,2) not null default 0,
  journal_entry_id bigint
    references public.journal_entries(id) on delete restrict,
  request_key text,
  note text,
  metadata jsonb not null default '{}'::jsonb,
  recorded_by_admin_user_id uuid,
  created_at timestamptz not null default now()
);

create unique index if not exists flexy_account_events_request_unique
  on public.flexy_account_events(account_id,request_key)
  where request_key is not null and btrim(request_key) <> '';

create index if not exists flexy_account_events_account_idx
  on public.flexy_account_events(account_id,created_at desc,id desc);

alter table public.flexy_accounts enable row level security;
alter table public.flexy_orders enable row level security;
alter table public.flexy_wallet_holds enable row level security;
alter table public.flexy_account_events enable row level security;

drop policy if exists "shop admin read flexy accounts" on public.flexy_accounts;
create policy "shop admin read flexy accounts"
on public.flexy_accounts for select to authenticated
using ((select private.is_shop_admin()));

drop policy if exists "shop admin read flexy orders" on public.flexy_orders;
create policy "shop admin read flexy orders"
on public.flexy_orders for select to authenticated
using ((select private.is_shop_admin()));

drop policy if exists "shop admin read flexy wallet holds" on public.flexy_wallet_holds;
create policy "shop admin read flexy wallet holds"
on public.flexy_wallet_holds for select to authenticated
using ((select private.is_shop_admin()));

drop policy if exists "shop admin read flexy account events" on public.flexy_account_events;
create policy "shop admin read flexy account events"
on public.flexy_account_events for select to authenticated
using ((select private.is_shop_admin()));

revoke insert,update,delete on public.flexy_accounts from anon,authenticated;
revoke insert,update,delete on public.flexy_orders from anon,authenticated;
revoke insert,update,delete on public.flexy_wallet_holds from anon,authenticated;
revoke insert,update,delete on public.flexy_account_events from anon,authenticated;

create or replace view public.flexy_account_balances
with (security_invoker = true)
as
select
  fa.id as account_id,
  fa.account_uuid,
  fa.display_name,
  fa.username,
  fa.status,
  fa.account_rate_percent,
  fa.allow_debt,
  fa.currency_code,
  fa.credit_ledger_account_id,
  fa.debt_ledger_account_id,
  coalesce(cb.credit_total - cb.debit_total,0)::numeric(18,2) as credit_balance,
  coalesce(db.debit_total - db.credit_total,0)::numeric(18,2) as debt_balance,
  coalesce(h.reserved_credit,0)::numeric(18,2) as reserved_credit,
  coalesce(h.reserved_debt,0)::numeric(18,2) as reserved_debt,
  greatest(
    coalesce(cb.credit_total - cb.debit_total,0) - coalesce(h.reserved_credit,0),
    0
  )::numeric(18,2) as available_credit,
  (
    coalesce(cb.credit_total - cb.debit_total,0)
    - coalesce(db.debit_total - db.credit_total,0)
  )::numeric(18,2) as net_position,
  fa.created_at,
  fa.updated_at
from public.flexy_accounts fa
left join public.account_balances cb on cb.account_id=fa.credit_ledger_account_id
left join public.account_balances db on db.account_id=fa.debt_ledger_account_id
left join (
  select
    h.account_id,
    sum(case when h.status in ('active','review') then h.credit_amount else 0 end) as reserved_credit,
    sum(case when h.status in ('active','review') then h.debt_amount else 0 end) as reserved_debt
  from public.flexy_wallet_holds h
  group by h.account_id
) h on h.account_id=fa.id;

revoke all on public.flexy_account_balances from anon;
grant select on public.flexy_account_balances to authenticated;

create or replace function private.flexy_control_account_id()
returns bigint
language sql
stable
security definer
set search_path=''
as $function$
  select a.id
  from public.accounts a
  where a.system_code='FLEXY_SUBLEDGER_CONTROL'
    and a.active=true
  limit 1;
$function$;

create or replace function private.flexy_post_journal(
  p_account_id bigint,
  p_event_type text,
  p_amount numeric,
  p_credit_delta numeric,
  p_debt_delta numeric,
  p_request_key text,
  p_note text,
  p_metadata jsonb,
  p_description text
)
returns table(event_id bigint,journal_entry_id bigint,reused boolean)
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_account public.flexy_accounts%rowtype;
  v_existing public.flexy_account_events%rowtype;
  v_control bigint;
  v_entry bigint;
  v_event bigint;
  v_debit_total numeric(18,2) := 0;
  v_credit_total numeric(18,2) := 0;
  v_credit_change numeric(18,2) := coalesce(p_credit_delta,0);
  v_debt_change numeric(18,2) := coalesce(p_debt_delta,0);
  v_control_net numeric(18,2);
  v_request text := nullif(btrim(coalesce(p_request_key,'')),'');
begin
  if not private.is_shop_admin() then
    raise exception 'PERMISSION_DENIED' using errcode='42501';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'INVALID_AMOUNT' using errcode='22023';
  end if;

  if p_event_type not in ('credit','debt','payment','refund','adjustment','reversal') then
    raise exception 'INVALID_EVENT_TYPE' using errcode='22023';
  end if;

  select * into v_account
  from public.flexy_accounts a
  where a.id=p_account_id
    and a.status <> 'archived'
  for update;

  if not found then
    raise exception 'FLEXY_ACCOUNT_NOT_FOUND' using errcode='P0002';
  end if;

  if v_request is not null then
    select * into v_existing
    from public.flexy_account_events e
    where e.account_id=p_account_id
      and e.request_key=v_request
    limit 1;

    if found then
      return query select v_existing.id,v_existing.journal_entry_id,true;
      return;
    end if;
  end if;

  v_control := private.flexy_control_account_id();
  if v_control is null then
    raise exception 'FLEXY_CONTROL_ACCOUNT_MISSING';
  end if;

  insert into public.journal_entries(
    description,status,source_type,branch_id,
    recorded_by_admin_user_id,notes
  )
  values (
    p_description,'draft','flexy_account',null,
    auth.uid(),nullif(btrim(coalesce(p_note,'')),'')
  )
  returning id into v_entry;

  -- Credit wallet balance is represented by a liability account:
  -- positive credit_delta => credit the liability, negative => debit it.
  if v_credit_change > 0 then
    insert into public.journal_lines(journal_entry_id,account_id,debit,credit,memo)
    values(v_entry,v_account.credit_ledger_account_id,0,v_credit_change,'رصيد Flexy');
    v_credit_total := v_credit_total + v_credit_change;
  elsif v_credit_change < 0 then
    insert into public.journal_lines(journal_entry_id,account_id,debit,credit,memo)
    values(v_entry,v_account.credit_ledger_account_id,abs(v_credit_change),0,'استهلاك/عكس رصيد Flexy');
    v_debit_total := v_debit_total + abs(v_credit_change);
  end if;

  -- Debt is represented by an asset account:
  -- positive debt_delta => debit receivable, negative => credit it.
  if v_debt_change > 0 then
    insert into public.journal_lines(journal_entry_id,account_id,debit,credit,memo)
    values(v_entry,v_account.debt_ledger_account_id,v_debt_change,0,'دين Flexy');
    v_debit_total := v_debit_total + v_debt_change;
  elsif v_debt_change < 0 then
    insert into public.journal_lines(journal_entry_id,account_id,debit,credit,memo)
    values(v_entry,v_account.debt_ledger_account_id,0,abs(v_debt_change),'تسديد/عكس دين Flexy');
    v_credit_total := v_credit_total + abs(v_debt_change);
  end if;

  v_control_net := v_debit_total - v_credit_total;

  if v_control_net > 0 then
    insert into public.journal_lines(journal_entry_id,account_id,debit,credit,memo)
    values(v_entry,v_control,0,v_control_net,'مقابل داخلي لمحفظة Flexy');
  elsif v_control_net < 0 then
    insert into public.journal_lines(journal_entry_id,account_id,debit,credit,memo)
    values(v_entry,v_control,abs(v_control_net),0,'مقابل داخلي لمحفظة Flexy');
  else
    -- A zero-net event would not produce a valid posted journal entry.
    raise exception 'ZERO_NET_FLEXY_EVENT' using errcode='22023';
  end if;

  update public.journal_entries
  set status='posted',posted_at=now()
  where id=v_entry;

  insert into public.flexy_account_events(
    account_id,event_type,amount,credit_delta,debt_delta,
    journal_entry_id,request_key,note,metadata,recorded_by_admin_user_id
  )
  values(
    p_account_id,p_event_type,p_amount,v_credit_change,v_debt_change,
    v_entry,v_request,nullif(btrim(coalesce(p_note,'')),''),
    coalesce(p_metadata,'{}'::jsonb),auth.uid()
  )
  returning id into v_event;

  update public.journal_entries
  set source_id=v_event
  where id=v_entry;

  return query select v_event,v_entry,false;
end;
$function$;

create or replace function public.admin_flexy_create_account(
  p_display_name text,
  p_username text default null,
  p_allow_debt boolean default false,
  p_account_rate_percent numeric default 0,
  p_notes text default null
)
returns table(
  account_uuid uuid,
  account_id bigint,
  display_name text
)
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_name text := btrim(coalesce(p_display_name,''));
  v_username text := nullif(btrim(coalesce(p_username,'')),'');
  v_credit bigint;
  v_debt bigint;
  v_id bigint;
  v_uuid uuid;
begin
  if not private.is_shop_admin() then
    raise exception 'PERMISSION_DENIED' using errcode='42501';
  end if;

  if v_name='' then
    raise exception 'INVALID_DISPLAY_NAME' using errcode='22023';
  end if;

  if coalesce(p_account_rate_percent,0) < 0 then
    raise exception 'INVALID_RATE' using errcode='22023';
  end if;

  insert into public.accounts(
    branch_id,name,account_type,account_subtype,currency_code,active,is_system,notes
  )
  values(
    null,'رصيد Flexy - '||v_name,'liability','flexy_customer_credit',
    'DZD',true,false,'حساب دفتر رصيد Flexy'
  )
  returning id into v_credit;

  insert into public.accounts(
    branch_id,name,account_type,account_subtype,currency_code,active,is_system,notes
  )
  values(
    null,'دين Flexy - '||v_name,'asset','flexy_customer_debt',
    'DZD',true,false,'حساب دفتر دين Flexy'
  )
  returning id into v_debt;

  insert into public.flexy_accounts(
    display_name,username,status,account_rate_percent,allow_debt,
    credit_ledger_account_id,debt_ledger_account_id,notes,
    created_by_admin_user_id
  )
  values(
    v_name,v_username,'active',coalesce(p_account_rate_percent,0),coalesce(p_allow_debt,false),
    v_credit,v_debt,nullif(btrim(coalesce(p_notes,'')),''),auth.uid()
  )
  returning id,flexy_accounts.account_uuid into v_id,v_uuid;

  return query select v_uuid,v_id,v_name;
end;
$function$;

create or replace function public.admin_flexy_update_account(
  p_account_uuid uuid,
  p_display_name text default null,
  p_username text default null,
  p_status text default null,
  p_allow_debt boolean default null,
  p_account_rate_percent numeric default null,
  p_notes text default null
)
returns boolean
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_account public.flexy_accounts%rowtype;
begin
  if not private.is_shop_admin() then
    raise exception 'PERMISSION_DENIED' using errcode='42501';
  end if;

  select * into v_account
  from public.flexy_accounts a
  where a.account_uuid=p_account_uuid
  for update;

  if not found then raise exception 'FLEXY_ACCOUNT_NOT_FOUND' using errcode='P0002'; end if;

  if p_status is not null and p_status not in ('active','blocked','archived') then
    raise exception 'INVALID_STATUS' using errcode='22023';
  end if;
  if p_account_rate_percent is not null and p_account_rate_percent < 0 then
    raise exception 'INVALID_RATE' using errcode='22023';
  end if;

  update public.flexy_accounts
  set display_name=case
        when p_display_name is null then display_name
        when nullif(btrim(p_display_name),'') is null then display_name
        else btrim(p_display_name)
      end,
      username=case
        when p_username is null then username
        else nullif(btrim(p_username),'')
      end,
      status=coalesce(p_status,status),
      allow_debt=coalesce(p_allow_debt,allow_debt),
      account_rate_percent=coalesce(p_account_rate_percent,account_rate_percent),
      notes=case when p_notes is null then notes else nullif(btrim(p_notes),'') end,
      updated_at=now()
  where account_uuid=p_account_uuid;

  return true;
end;
$function$;

create or replace function public.admin_flexy_add_credit(
  p_account_uuid uuid,
  p_amount numeric,
  p_note text default null,
  p_request_key text default null
)
returns table(event_id bigint,reused boolean)
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_id bigint;
  v_result record;
begin
  if not private.is_shop_admin() then raise exception 'PERMISSION_DENIED' using errcode='42501'; end if;
  select a.id into v_id from public.flexy_accounts a where a.account_uuid=p_account_uuid;
  if v_id is null then raise exception 'FLEXY_ACCOUNT_NOT_FOUND' using errcode='P0002'; end if;

  select * into v_result
  from private.flexy_post_journal(
    v_id,'credit',p_amount,p_amount,0,p_request_key,p_note,'{}'::jsonb,'إضافة رصيد Flexy'
  );

  return query select v_result.event_id,v_result.reused;
end;
$function$;

create or replace function public.admin_flexy_add_debt(
  p_account_uuid uuid,
  p_amount numeric,
  p_note text default null,
  p_request_key text default null
)
returns table(event_id bigint,reused boolean)
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_id bigint;
  v_result record;
begin
  if not private.is_shop_admin() then raise exception 'PERMISSION_DENIED' using errcode='42501'; end if;
  select a.id into v_id from public.flexy_accounts a where a.account_uuid=p_account_uuid;
  if v_id is null then raise exception 'FLEXY_ACCOUNT_NOT_FOUND' using errcode='P0002'; end if;

  select * into v_result
  from private.flexy_post_journal(
    v_id,'debt',p_amount,0,p_amount,p_request_key,p_note,'{}'::jsonb,'إضافة دين Flexy'
  );

  return query select v_result.event_id,v_result.reused;
end;
$function$;

create or replace function public.admin_flexy_record_payment(
  p_account_uuid uuid,
  p_amount numeric,
  p_note text default null,
  p_request_key text default null
)
returns table(
  event_id bigint,
  debt_paid numeric,
  credit_added numeric,
  reused boolean
)
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_account public.flexy_accounts%rowtype;
  v_debt numeric(18,2);
  v_debt_paid numeric(18,2);
  v_credit_added numeric(18,2);
  v_existing public.flexy_account_events%rowtype;
  v_result record;
  v_request text := nullif(btrim(coalesce(p_request_key,'')),'');
begin
  if not private.is_shop_admin() then raise exception 'PERMISSION_DENIED' using errcode='42501'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'INVALID_AMOUNT' using errcode='22023'; end if;

  select * into v_account
  from public.flexy_accounts a
  where a.account_uuid=p_account_uuid
    and a.status <> 'archived'
  for update;

  if not found then raise exception 'FLEXY_ACCOUNT_NOT_FOUND' using errcode='P0002'; end if;

  if v_request is not null then
    select * into v_existing
    from public.flexy_account_events e
    where e.account_id=v_account.id and e.request_key=v_request
    limit 1;
    if found then
      return query
      select
        v_existing.id,
        abs(least(v_existing.debt_delta,0)),
        greatest(v_existing.credit_delta,0),
        true;
      return;
    end if;
  end if;

  select coalesce(b.debt_balance,0) into v_debt
  from public.flexy_account_balances b
  where b.account_id=v_account.id;

  v_debt_paid := least(coalesce(v_debt,0),p_amount);
  v_credit_added := p_amount-v_debt_paid;

  select * into v_result
  from private.flexy_post_journal(
    v_account.id,
    'payment',
    p_amount,
    v_credit_added,
    -v_debt_paid,
    v_request,
    p_note,
    jsonb_build_object('debt_paid',v_debt_paid,'credit_added',v_credit_added),
    'دفع حساب Flexy'
  );

  return query select v_result.event_id,v_debt_paid,v_credit_added,v_result.reused;
end;
$function$;

create or replace function public.admin_flexy_refund_to_credit(
  p_account_uuid uuid,
  p_amount numeric,
  p_note text default null,
  p_request_key text default null
)
returns table(event_id bigint,reused boolean)
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_id bigint;
  v_result record;
begin
  if not private.is_shop_admin() then raise exception 'PERMISSION_DENIED' using errcode='42501'; end if;
  select a.id into v_id from public.flexy_accounts a where a.account_uuid=p_account_uuid;
  if v_id is null then raise exception 'FLEXY_ACCOUNT_NOT_FOUND' using errcode='P0002'; end if;

  select * into v_result
  from private.flexy_post_journal(
    v_id,'refund',p_amount,p_amount,0,p_request_key,p_note,'{}'::jsonb,'إرجاع إلى رصيد Flexy'
  );

  return query select v_result.event_id,v_result.reused;
end;
$function$;

create or replace function public.admin_flexy_create_order_hold(
  p_account_uuid uuid,
  p_phone text,
  p_face_amount numeric,
  p_wallet_charge_amount numeric,
  p_request_key text,
  p_service_type text default 'offer',
  p_family text default null,
  p_network_index text default null
)
returns table(
  order_uuid uuid,
  status text,
  credit_reserved numeric,
  debt_reserved numeric,
  reused boolean
)
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_account public.flexy_accounts%rowtype;
  v_balance record;
  v_existing public.flexy_orders%rowtype;
  v_phone text := regexp_replace(coalesce(p_phone,''),'[^0-9]','','g');
  v_request text := btrim(coalesce(p_request_key,''));
  v_charge numeric(18,2);
  v_credit numeric(18,2);
  v_debt numeric(18,2);
  v_order_id bigint;
  v_order_uuid uuid;
begin
  if not private.is_shop_admin() then raise exception 'PERMISSION_DENIED' using errcode='42501'; end if;
  if v_phone !~ '^0[5-7][0-9]{8}$' then raise exception 'INVALID_PHONE' using errcode='22023'; end if;
  if p_face_amount is null or p_face_amount <= 0 then raise exception 'INVALID_FACE_AMOUNT' using errcode='22023'; end if;
  if p_wallet_charge_amount is null or p_wallet_charge_amount <= 0 then raise exception 'INVALID_CHARGE_AMOUNT' using errcode='22023'; end if;
  if v_request='' then raise exception 'REQUEST_KEY_REQUIRED' using errcode='22023'; end if;

  select * into v_account
  from public.flexy_accounts a
  where a.account_uuid=p_account_uuid
  for update;

  if not found then raise exception 'FLEXY_ACCOUNT_NOT_FOUND' using errcode='P0002'; end if;
  if v_account.status <> 'active' then raise exception 'FLEXY_ACCOUNT_NOT_ACTIVE' using errcode='42501'; end if;

  select * into v_existing
  from public.flexy_orders o
  where o.account_id=v_account.id and o.request_key=v_request
  limit 1;

  if found then
    return query
    select
      v_existing.order_uuid,
      v_existing.status,
      coalesce((select h.credit_amount from public.flexy_wallet_holds h where h.order_id=v_existing.id),0),
      coalesce((select h.debt_amount from public.flexy_wallet_holds h where h.order_id=v_existing.id),0),
      true;
    return;
  end if;

  select * into v_balance
  from public.flexy_account_balances b
  where b.account_id=v_account.id;

  v_charge := p_wallet_charge_amount;
  v_credit := least(coalesce(v_balance.available_credit,0),v_charge);
  v_debt := v_charge-v_credit;

  if v_debt > 0 and not v_account.allow_debt then
    raise exception 'INSUFFICIENT_FLEXY_CREDIT' using errcode='P0001';
  end if;

  insert into public.flexy_orders(
    account_id,request_key,phone,operator,service_type,family,network_index,
    face_amount,wallet_charge_amount,rate_percent_applied,
    funding_mode,status,created_by_admin_user_id,reserved_at
  )
  values(
    v_account.id,v_request,v_phone,'mobilis',coalesce(nullif(btrim(p_service_type),''),'offer'),
    nullif(btrim(coalesce(p_family,'')),''),nullif(btrim(coalesce(p_network_index,'')),''),
    p_face_amount,v_charge,v_account.account_rate_percent,
    case
      when v_credit>0 and v_debt>0 then 'mixed'
      when v_credit>0 then 'credit'
      else 'debt'
    end,
    'reserved',auth.uid(),now()
  )
  returning id,flexy_orders.order_uuid into v_order_id,v_order_uuid;

  insert into public.flexy_wallet_holds(
    order_id,account_id,credit_amount,debt_amount,status
  )
  values(v_order_id,v_account.id,v_credit,v_debt,'active');

  return query select v_order_uuid,'reserved'::text,v_credit,v_debt,false;
end;
$function$;

create or replace function public.admin_flexy_list_accounts(
  p_search text default null,
  p_status text default null,
  p_limit integer default 25,
  p_offset integer default 0
)
returns table(
  account_uuid uuid,
  account_id bigint,
  display_name text,
  username text,
  status text,
  account_rate_percent numeric,
  allow_debt boolean,
  credit_balance numeric,
  debt_balance numeric,
  reserved_credit numeric,
  reserved_debt numeric,
  available_credit numeric,
  total_count bigint,
  updated_at timestamptz
)
language sql
security definer
set search_path=''
as $function$
  select
    b.account_uuid,b.account_id,b.display_name,b.username,b.status,
    b.account_rate_percent,b.allow_debt,b.credit_balance,b.debt_balance,
    b.reserved_credit,b.reserved_debt,b.available_credit,
    count(*) over() as total_count,b.updated_at
  from public.flexy_account_balances b
  where private.is_shop_admin()
    and (
      nullif(btrim(coalesce(p_search,'')),'') is null
      or b.display_name ilike '%'||btrim(p_search)||'%'
      or coalesce(b.username,'') ilike '%'||btrim(p_search)||'%'
      or b.account_id::text=btrim(p_search)
    )
    and (
      nullif(btrim(coalesce(p_status,'')),'') is null
      or b.status=btrim(p_status)
    )
  order by
    case when b.status='active' then 0 when b.status='blocked' then 1 else 2 end,
    b.updated_at desc,
    b.account_id desc
  limit greatest(1,least(coalesce(p_limit,25),100))
  offset greatest(coalesce(p_offset,0),0);
$function$;

create or replace function public.admin_flexy_get_account(p_account_uuid uuid)
returns table(
  account_uuid uuid,
  account_id bigint,
  display_name text,
  username text,
  status text,
  account_rate_percent numeric,
  allow_debt boolean,
  credit_balance numeric,
  debt_balance numeric,
  reserved_credit numeric,
  reserved_debt numeric,
  available_credit numeric,
  net_position numeric,
  notes text,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
security definer
set search_path=''
as $function$
  select
    b.account_uuid,b.account_id,b.display_name,b.username,b.status,
    b.account_rate_percent,b.allow_debt,b.credit_balance,b.debt_balance,
    b.reserved_credit,b.reserved_debt,b.available_credit,b.net_position,
    a.notes,b.created_at,b.updated_at
  from public.flexy_account_balances b
  join public.flexy_accounts a on a.id=b.account_id
  where private.is_shop_admin()
    and b.account_uuid=p_account_uuid;
$function$;

create or replace function public.admin_flexy_list_account_events(
  p_account_uuid uuid,
  p_limit integer default 25,
  p_offset integer default 0
)
returns table(
  event_uuid uuid,
  event_id bigint,
  event_type text,
  amount numeric,
  credit_delta numeric,
  debt_delta numeric,
  note text,
  metadata jsonb,
  order_uuid uuid,
  created_at timestamptz,
  total_count bigint
)
language sql
security definer
set search_path=''
as $function$
  select
    e.event_uuid,e.id,e.event_type,e.amount,e.credit_delta,e.debt_delta,
    e.note,e.metadata,o.order_uuid,e.created_at,count(*) over()
  from public.flexy_account_events e
  join public.flexy_accounts a on a.id=e.account_id
  left join public.flexy_orders o on o.id=e.order_id
  where private.is_shop_admin()
    and a.account_uuid=p_account_uuid
  order by e.created_at desc,e.id desc
  limit greatest(1,least(coalesce(p_limit,25),100))
  offset greatest(coalesce(p_offset,0),0);
$function$;

create or replace function public.admin_flexy_list_orders(
  p_status text default null,
  p_account_uuid uuid default null,
  p_limit integer default 25,
  p_offset integer default 0
)
returns table(
  order_uuid uuid,
  order_id bigint,
  account_uuid uuid,
  account_name text,
  phone text,
  family text,
  network_index text,
  face_amount numeric,
  wallet_charge_amount numeric,
  funding_mode text,
  status text,
  result_code text,
  result_text text,
  created_at timestamptz,
  completed_at timestamptz,
  total_count bigint
)
language sql
security definer
set search_path=''
as $function$
  select
    o.order_uuid,o.id,a.account_uuid,a.display_name,o.phone,o.family,o.network_index,
    o.face_amount,o.wallet_charge_amount,o.funding_mode,o.status,o.result_code,o.result_text,
    o.created_at,o.completed_at,count(*) over()
  from public.flexy_orders o
  join public.flexy_accounts a on a.id=o.account_id
  where private.is_shop_admin()
    and (
      nullif(btrim(coalesce(p_status,'')),'') is null
      or o.status=btrim(p_status)
    )
    and (
      p_account_uuid is null
      or a.account_uuid=p_account_uuid
    )
  order by o.created_at desc,o.id desc
  limit greatest(1,least(coalesce(p_limit,25),100))
  offset greatest(coalesce(p_offset,0),0);
$function$;

revoke all on function public.admin_flexy_create_account(text,text,boolean,numeric,text) from public,anon;
revoke all on function public.admin_flexy_update_account(uuid,text,text,text,boolean,numeric,text) from public,anon;
revoke all on function public.admin_flexy_add_credit(uuid,numeric,text,text) from public,anon;
revoke all on function public.admin_flexy_add_debt(uuid,numeric,text,text) from public,anon;
revoke all on function public.admin_flexy_record_payment(uuid,numeric,text,text) from public,anon;
revoke all on function public.admin_flexy_refund_to_credit(uuid,numeric,text,text) from public,anon;
revoke all on function public.admin_flexy_create_order_hold(uuid,text,numeric,numeric,text,text,text,text) from public,anon;
revoke all on function public.admin_flexy_list_accounts(text,text,integer,integer) from public,anon;
revoke all on function public.admin_flexy_get_account(uuid) from public,anon;
revoke all on function public.admin_flexy_list_account_events(uuid,integer,integer) from public,anon;
revoke all on function public.admin_flexy_list_orders(text,uuid,integer,integer) from public,anon;

grant execute on function public.admin_flexy_create_account(text,text,boolean,numeric,text) to authenticated;
grant execute on function public.admin_flexy_update_account(uuid,text,text,text,boolean,numeric,text) to authenticated;
grant execute on function public.admin_flexy_add_credit(uuid,numeric,text,text) to authenticated;
grant execute on function public.admin_flexy_add_debt(uuid,numeric,text,text) to authenticated;
grant execute on function public.admin_flexy_record_payment(uuid,numeric,text,text) to authenticated;
grant execute on function public.admin_flexy_refund_to_credit(uuid,numeric,text,text) to authenticated;
grant execute on function public.admin_flexy_create_order_hold(uuid,text,numeric,numeric,text,text,text,text) to authenticated;
grant execute on function public.admin_flexy_list_accounts(text,text,integer,integer) to authenticated;
grant execute on function public.admin_flexy_get_account(uuid) to authenticated;
grant execute on function public.admin_flexy_list_account_events(uuid,integer,integer) to authenticated;
grant execute on function public.admin_flexy_list_orders(text,uuid,integer,integer) to authenticated;
