-- MyTool shop: lightweight worker accounts without Supabase Auth
-- Owner/admin continues to use Supabase Auth.
-- Worker passwords are never stored as plain text: the trigger hashes them on insert/update.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.worker_accounts (
    id bigint generated by default as identity primary key,
    username text not null,
    password text not null,
    phone text,
    nickname text,
    staff_id bigint not null references public.staff(id) on delete restrict,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists worker_accounts_username_unique
on public.worker_accounts (lower(username));

create table if not exists public.worker_sessions (
    id bigint generated by default as identity primary key,
    worker_id bigint not null references public.worker_accounts(id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    last_used_at timestamptz not null default now()
);

alter table public.worker_accounts enable row level security;
alter table public.worker_sessions enable row level security;

-- Only real Supabase-authenticated admin accounts can manage these tables directly.
drop policy if exists "authenticated worker accounts access" on public.worker_accounts;
create policy "authenticated worker accounts access"
on public.worker_accounts
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated worker sessions access" on public.worker_sessions;
create policy "authenticated worker sessions access"
on public.worker_sessions
for all
to authenticated
using (true)
with check (true);

create or replace function public.hash_worker_password()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    if tg_op = 'INSERT' or new.password is distinct from old.password then
        if new.password is null or length(new.password) < 4 then
            raise exception 'Password must be at least 4 characters';
        end if;

        -- Keep an already-hashed bcrypt value unchanged; otherwise hash plaintext.
        if new.password !~ '^\$2[aby]\$' then
            new.password := crypt(new.password, gen_salt('bf', 10));
        end if;
    end if;

    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists worker_accounts_hash_password on public.worker_accounts;
create trigger worker_accounts_hash_password
before insert or update on public.worker_accounts
for each row execute function public.hash_worker_password();

create or replace function public.worker_login(p_username text, p_password text)
returns table (
    session_token text,
    worker_id bigint,
    staff_id bigint,
    nickname text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    v_worker public.worker_accounts%rowtype;
    v_token text;
begin
    select * into v_worker
    from public.worker_accounts
    where lower(username) = lower(trim(p_username))
      and active = true
    limit 1;

    if not found or v_worker.password <> crypt(p_password, v_worker.password) then
        raise exception 'INVALID_LOGIN';
    end if;

    v_token := encode(gen_random_bytes(32), 'hex');

    insert into public.worker_sessions (worker_id, token_hash, expires_at)
    values (
        v_worker.id,
        encode(digest(v_token, 'sha256'), 'hex'),
        now() + interval '30 days'
    );

    return query
    select v_token, v_worker.id, v_worker.staff_id,
           coalesce(nullif(v_worker.nickname, ''), v_worker.username);
end;
$$;

create or replace function public.worker_get_catalog(p_session_token text)
returns table (
    product_id bigint,
    name text,
    stock_quantity bigint
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    v_session_id bigint;
begin
    select ws.id into v_session_id
    from public.worker_sessions ws
    join public.worker_accounts wa on wa.id = ws.worker_id
    where ws.token_hash = encode(digest(p_session_token, 'sha256'), 'hex')
      and ws.expires_at > now()
      and wa.active = true
    limit 1;

    if v_session_id is null then
        raise exception 'INVALID_SESSION';
    end if;

    update public.worker_sessions
    set last_used_at = now()
    where id = v_session_id;

    return query
    select i.product_id, i.name, i.stock_quantity::bigint
    from public.inventory_summary i
    order by i.product_id;
end;
$$;

create or replace function public.worker_create_sale(
    p_session_token text,
    p_product_id bigint,
    p_quantity integer,
    p_unit_price numeric,
    p_notes text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    v_session_id bigint;
    v_staff_id bigint;
    v_sale_id bigint;
begin
    select ws.id, wa.staff_id
    into v_session_id, v_staff_id
    from public.worker_sessions ws
    join public.worker_accounts wa on wa.id = ws.worker_id
    where ws.token_hash = encode(digest(p_session_token, 'sha256'), 'hex')
      and ws.expires_at > now()
      and wa.active = true
    limit 1;

    if v_session_id is null then
        raise exception 'INVALID_SESSION';
    end if;

    if p_quantity is null or p_quantity < 1 then
        raise exception 'INVALID_QUANTITY';
    end if;

    if p_unit_price is null or p_unit_price < 0 then
        raise exception 'INVALID_PRICE';
    end if;

    if not exists (select 1 from public.products where id = p_product_id) then
        raise exception 'INVALID_PRODUCT';
    end if;

    insert into public.sales (product_id, quantity, unit_price, sold_by, notes)
    values (p_product_id, p_quantity, p_unit_price, v_staff_id, nullif(trim(p_notes), ''))
    returning id into v_sale_id;

    update public.worker_sessions
    set last_used_at = now()
    where id = v_session_id;

    return v_sale_id;
end;
$$;

create or replace function public.worker_logout(p_session_token text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    delete from public.worker_sessions
    where token_hash = encode(digest(p_session_token, 'sha256'), 'hex');
    return true;
end;
$$;

-- Do not expose the tables to anonymous users; only expose the narrow RPC functions.
revoke all on table public.worker_accounts from anon;
revoke all on table public.worker_sessions from anon;

revoke all on function public.worker_login(text, text) from public;
revoke all on function public.worker_get_catalog(text) from public;
revoke all on function public.worker_create_sale(text, bigint, integer, numeric, text) from public;
revoke all on function public.worker_logout(text) from public;

grant execute on function public.worker_login(text, text) to anon, authenticated;
grant execute on function public.worker_get_catalog(text) to anon, authenticated;
grant execute on function public.worker_create_sale(text, bigint, integer, numeric, text) to anon, authenticated;
grant execute on function public.worker_logout(text) to anon, authenticated;
