(() => {
  const D=window.AMORTECH_INDEX;
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const statusName={canonical:'دفعة أصلية',confirmed:'مؤكدة',deduped:'مكررة دُمجت',unused:'لم يستخدم بعد'};
  $('stats').innerHTML=[['الدفعات',D.summary.batches],['بطاقات داخل الدفعات',D.summary.batchCards],['تتبع مصدر منفرد',D.summary.trackedCards],['مراجع فريدة',D.summary.uniqueReferences]].map(([t,n])=>`<div class="stat"><b>${n}</b><span>${t}</span></div>`).join('');
  const batchByHash=new Map(Object.entries(D.lookup).map(([hash,v])=>[hash,{kind:'batch',batch:D.batches[v[0]],index:v[1]}]));
  Object.entries(D.tracked).forEach(([hash,v])=>batchByHash.set(hash,{kind:'tracked',source:v[0],note:v[1]}));
  async function sha256(text){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}
  async function searchCard(){const el=$('cardResult'),raw=$('cardSearch').value.replace(/\D/g,'');el.hidden=false;if(raw.length!==15){el.className='resultBox bad';el.textContent='أدخل رقم Mobilis من 15 رقمًا بالضبط.';return}const hit=batchByHash.get(await sha256(raw));if(!hit){el.className='resultBox bad';el.textContent='لم أجد هذه البطاقة في الدفعات المستخرجة من سجل @AmorTechDZ.';return}el.className='resultBox ok';if(hit.kind==='batch'){const b=hit.batch;el.innerHTML=`<b>تم العثور ✓</b><br>الدفعة: <b>${esc(b.name)}</b><br>التاريخ: ${esc(b.date)} · رقمها داخل الدفعة: ${hit.index}/${b.count}<br>المصدر: ${esc(b.source)}`;}else{el.innerHTML=`<b>تم العثور ✓</b><br>تتبع منفرد — المصدر: <b>${esc(hit.source)}</b><br>${esc(hit.note)}`;}}
  $('cardSearchBtn').onclick=searchCard;$('cardSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchCard()});
  const sorted=[...D.batches].sort((a,b)=>{if(a.status==='unused'&&b.status!=='unused')return-1;if(b.status==='unused'&&a.status!=='unused')return 1;const pa=a.date.split('/').reverse().join(''),pb=b.date.split('/').reverse().join('');return pb.localeCompare(pa)});
  $('batches').innerHTML=sorted.map(b=>`<article class="batch ${b.status==='unused'?'priority':''}"><div class="batchHead"><div><h3>${esc(b.name)}</h3><div class="meta">${esc(b.date)} · ${esc(b.source)} · ${esc(statusName[b.status]||b.status)}</div></div><span class="countBadge">${b.count} بطاقة</span></div>${b.aliases?.length?`<div class="alias"><b>نسخ/أسماء مرتبطة لم تُكرر كدفعة:</b><br>${b.aliases.map(esc).join('<br>')}</div>`:''}</article>`).join('');
  $('tracked').innerHTML=Object.values(D.tracked).map(v=>`<article class="batch"><div class="batchHead"><div><h3>${esc(v[0])}</h3><div class="meta">${esc(v[1])}</div></div><span class="countBadge">تتبع منفرد</span></div></article>`).join('');
  const sectionRank=['قواعد البطاقات','Flexy / Tehna Connect Core','MyTool / المحل','مشاريع ومراجع','أوامر وصيانة'];
  function renderNotes(q=''){const needle=q.trim().toLowerCase();const hits=D.notes.filter(n=>!needle||(`${n.section} ${n.title} ${n.text}`).toLowerCase().includes(needle)).sort((a,b)=>b.priority-a.priority);const groups=new Map();hits.forEach(n=>{if(!groups.has(n.section))groups.set(n.section,[]);groups.get(n.section).push(n)});const order=[...groups.keys()].sort((a,b)=>{const ai=sectionRank.indexOf(a),bi=sectionRank.indexOf(b);return (ai<0?99:ai)-(bi<0?99:bi)});$('notes').innerHTML=order.length?order.map(section=>`<div class="noteGroup"><h2>${esc(section)}</h2>${groups.get(section).map(n=>`<article class="noteItem"><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><span class="sourceTag">أهمية ${n.priority}</span></article>`).join('')}</div>`).join(''):'<div class="empty">لا توجد نتيجة مطابقة.</div>'}
  renderNotes();$('noteSearch').addEventListener('input',e=>renderNotes(e.target.value));$('clearSearch').onclick=()=>{$('noteSearch').value='';renderNotes();$('noteSearch').focus()};
  $('excluded').innerHTML='<ul>'+D.excluded.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>';
})();
